// Generated by scripts/build-ios-layout.mjs. Do not edit.
var LWFALayout = (function(exports) {
	Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
	//#region packages/shell/src/generated/config.ts
	/**
	* Column widths, as fractions of the viewport.
	*
	* Presets rather than free resizing, because a column width change is an
	* `xdg_shell configure` and native apps re-layout from scratch rather than
	* reflowing. Cycling between a few known sizes keeps that rare and predictable;
	* a drag handle would fire one per frame.
	*/
	var WIDTH_PRESETS = [
		.3333333333333333,
		.5,
		.6666666666666667,
		.9,
		.99
	];
	/** Which way the strip runs. "auto" follows the viewport's long axis. */
	var ORIENTATION = "auto";
	/**
	* The spring windows move on.
	*
	* Shared with the engine, which integrates the identical parameters for the
	* physical display. See [animation] in configs/defaults.toml.
	*/
	var WINDOW_SPRING = {
		stiffness: 1e3,
		damping: 66,
		mass: 1
	};
	//#endregion
	//#region packages/shell/src/strip.ts
	var DEFAULT_CONFIG = {
		gap: 12,
		defaultWidth: 3,
		minWidth: 240,
		centreFocused: true,
		orientation: ORIENTATION
	};
	/**
	* The machine's defaults with the device's layout preferences over them.
	*
	* Takes the three fields structurally rather than importing the preferences
	* module, so this file still depends on nothing. It exists because more than
	* one place needs the config the session is actually running under, and two
	* copies of this would drift: a panel measuring with the default orientation
	* while the strip ran vertically would answer questions about the wrong axis.
	*/
	function configFrom(prefs) {
		return {
			...DEFAULT_CONFIG,
			orientation: prefs.orientation,
			centreFocused: prefs.centreFocused,
			defaultWidth: Math.min(Math.max(0, prefs.defaultWidth), WIDTH_PRESETS.length - 1)
		};
	}
	var emptyWorkspace = () => ({
		columns: [],
		focus: 0,
		viewOffset: 0,
		fullscreen: null,
		fit: false
	});
	/**
	* Workspaces are dynamic, niri-style: there is always exactly one empty one at
	* the end, so a new workspace is always one move away and none linger empty.
	*/
	var EMPTY = {
		workspaces: [emptyWorkspace()],
		focus: 0
	};
	function orientationOf(output, config) {
		if (config.orientation !== "auto") return config.orientation;
		return output.height > output.width ? "vertical" : "horizontal";
	}
	/** Viewport extent along the axis the strip scrolls. */
	function mainLength(output, config) {
		return orientationOf(output, config) === "horizontal" ? output.width : output.height;
	}
	/** Viewport extent across the strip, which a column fills. */
	function crossLength(output, config) {
		return orientationOf(output, config) === "horizontal" ? output.height : output.width;
	}
	function clampIndex(index, length) {
		if (length <= 0) return 0;
		return Math.min(Math.max(index, 0), length - 1);
	}
	function presetWidth(preset, output, config) {
		return Math.max(Math.round(mainLength(output, config) * WIDTH_PRESETS[preset]), config.minWidth);
	}
	/**
	* Extent of every column when the workspace is fitted.
	*
	* The gaps come out of the viewport *first*, so `count` columns and the
	* `count + 1` gaps around and between them add up to exactly the viewport and
	* the last column ends flush with its edge. This is the arithmetic the width
	* presets do not do: 50% of the viewport twice is three gaps too wide.
	*
	* Still floored at `minWidth`, so a workspace with more columns than can
	* honestly fit does not shrink them to slivers. Past that point the row is
	* wider than the screen and scrolling comes back on its own; see
	* [`fitsOnScreen`].
	*/
	function fittedWidth(count, output, config) {
		if (count <= 0) return mainLength(output, config);
		const available = mainLength(output, config) - config.gap * (count + 1);
		return Math.max(Math.floor(available / count), config.minWidth);
	}
	/** Whether a fitted workspace's columns actually all fit. */
	function fitsOnScreen(count, output, config) {
		if (count <= 0) return true;
		const width = fittedWidth(count, output, config);
		return config.gap * (count + 1) + width * count <= mainLength(output, config);
	}
	/**
	* The width every column takes, or `undefined` to use each column's preset.
	*
	* One value for the whole workspace rather than a per-column question,
	* because that is exactly what fitting means. Computed once by the callers
	* that walk the columns, so a strip of twenty does not recompute it twenty
	* times.
	*/
	function fitOverride(ws, output, config) {
		return ws.fit ? fittedWidth(ws.columns.length, output, config) : void 0;
	}
	function columnWidth(column, output, config, fitted) {
		return fitted ?? presetWidth(column.width, output, config);
	}
	/**
	* Extent available to a column across the strip, before any internal stacking.
	*
	* Full height in landscape, full width in portrait.
	*/
	function columnHeight(output, config) {
		return Math.max(crossLength(output, config) - config.gap * 2, 1);
	}
	/**
	* Balanced window groups, with the same policy in the browser and iPad.
	* Choose rows using the worst cell aspect ratio and the difference in cell
	* areas. Recursive half-splits gave odd subgroups unequal areas and could
	* change a whole branch's orientation at a one-pixel aspect-ratio boundary.
	* This is a grid for an existing group, not Hyprland's focus-driven BSP tree.
	*/
	function tile(box, count, gap) {
		if (count <= 0) return [];
		if (count <= 1) return [box];
		const portrait = box.height > box.width;
		const width = portrait ? box.height : box.width;
		const height = portrait ? box.width : box.height;
		const spacing = Math.max(0, gap);
		const usable = (length, parts) => {
			const gutter = parts <= 1 ? 0 : Math.min(spacing, Math.max(0, (length - parts) / (parts - 1)));
			return {
				gutter,
				length: length - gutter * (parts - 1)
			};
		};
		let rows = 1;
		let best = Infinity;
		for (let candidate = 1; candidate <= count; candidate++) {
			const small = Math.floor(count / candidate);
			const large = Math.ceil(count / candidate);
			const cellHeight = usable(height, candidate).length / candidate;
			const narrow = usable(width, large).length / large;
			const wide = usable(width, small).length / small;
			const score = Math.max(Math.abs(Math.log(narrow / cellHeight)), Math.abs(Math.log(wide / cellHeight))) + Math.log(wide / narrow);
			if (score < best - 1e-9) {
				best = score;
				rows = candidate;
			}
		}
		const split = (length, parts) => {
			const { gutter, length: available } = usable(length, parts);
			const edge = (index) => available >= parts ? Math.floor(available * index / parts) : available * index / parts;
			return Array.from({ length: parts }, (_, index) => ({
				start: edge(index) + gutter * index,
				size: edge(index + 1) - edge(index)
			}));
		};
		const cells = [];
		for (const [row, vertical] of split(height, rows).entries()) {
			const columns = Math.floor(count / rows) + (row < count % rows ? 1 : 0);
			for (const horizontal of split(width, columns)) cells.push(portrait ? {
				x: box.x + vertical.start,
				y: box.y + horizontal.start,
				width: vertical.size,
				height: horizontal.size
			} : {
				x: box.x + horizontal.start,
				y: box.y + vertical.start,
				width: horizontal.size,
				height: vertical.size
			});
		}
		return cells;
	}
	/**
	* Where column `index` starts along the strip, before the view offset.
	*
	* That is an x in landscape and a y in portrait. Extents vary per column, so
	* this accumulates rather than multiplying.
	*/
	function columnX(columns, index, output, config, fitted) {
		let x = config.gap;
		for (let i = 0; i < index && i < columns.length; i++) x += columnWidth(columns[i], output, config, fitted) + config.gap;
		return x;
	}
	function currentWorkspace(state) {
		return state.workspaces[clampIndex(state.focus, state.workspaces.length)] ?? emptyWorkspace();
	}
	/**
	* Where the viewport should sit so the focused column is where you expect it.
	*
	* Two behaviours, chosen by `config.centreFocused`:
	*
	* **Centred** puts the focused column in the middle of the viewport. Focus
	* always lands in the same place, so moving along the strip is a predictable
	* motion rather than a scroll you have to read, and both neighbours peek in at
	* the edges so it is obvious there is more strip in each direction. That
	* matters most on a tablet, where there is no keyboard to tell you where you
	* are. niri calls this `center-focused-column` and it is the reason this
	* project follows niri's model in the first place.
	*
	* **Minimal** scrolls the least distance that makes the column fully visible,
	* and leaves it alone if it already is. That wastes no motion and suits a wide
	* display where three columns fit and re-centring for every focus change would
	* be a lot of movement for no information.
	*/
	function targetOffset(state, output, config) {
		const ws = currentWorkspace(state);
		if (ws.columns.length === 0) return 0;
		const fitted = fitOverride(ws, output, config);
		if (ws.fit && fitsOnScreen(ws.columns.length, output, config)) return 0;
		const index = clampIndex(ws.focus, ws.columns.length);
		const column = ws.columns[index];
		const width = columnWidth(column, output, config, fitted);
		const left = columnX(ws.columns, index, output, config, fitted) - config.gap;
		const right = left + width + config.gap * 2;
		if (right - left >= mainLength(output, config)) return left;
		if (config.centreFocused) return left + config.gap + width / 2 - mainLength(output, config) / 2;
		if (left < ws.viewOffset) return left;
		if (right > ws.viewOffset + mainLength(output, config)) return right - mainLength(output, config);
		return ws.viewOffset;
	}
	/**
	* Target geometry for the focused workspace.
	*
	* Windows on other workspaces are omitted entirely. `SetLayout` is total, so the
	* engine hides them, which is exactly what switching workspaces should do.
	*/
	function layout(state, output, config) {
		const ws = currentWorkspace(state);
		if (ws.fullscreen !== null) return [{
			id: ws.fullscreen,
			rect: {
				x: 0,
				y: 0,
				width: output.width,
				height: output.height
			},
			z: 0
		}];
		const offset = ws.viewOffset;
		const out = [];
		let z = 0;
		const vertical = orientationOf(output, config) === "vertical";
		const fitted = fitOverride(ws, output, config);
		const breadth = columnHeight(output, config);
		ws.columns.forEach((column, index) => {
			const extent = columnWidth(column, output, config, fitted);
			const along = columnX(ws.columns, index, output, config, fitted) - offset;
			const cells = tile(vertical ? {
				x: config.gap,
				y: along,
				width: breadth,
				height: extent
			} : {
				x: along,
				y: config.gap,
				width: extent,
				height: breadth
			}, column.windows.length, config.gap);
			column.windows.forEach((id, at) => {
				const rect = cells[at];
				if (rect) out.push({
					id,
					rect,
					z: z++
				});
			});
		});
		return out;
	}
	/** Does this column intersect the viewport, and so deserve pixels? */
	function intersectsViewport(rect, output, config) {
		return orientationOf(output, config) === "vertical" ? rect.y + rect.height > 0 && rect.y < output.height : rect.x + rect.width > 0 && rect.x < output.width;
	}
	/**
	* Which of these windows to ask the engine for pixels for.
	*
	* The rules live together because they interact. A window is a candidate when
	* the viewport can actually show it; the fullscreen window is one no matter
	* what, because during fullscreen every other window has already been dropped
	* by `layout`, so the one window being watched gets the entire budget.
	*
	* `pauseInactive` is the global lever (see `Prefs.stream.pauseInactive`):
	* when it is on, only the focused window streams and every other candidate
	* freezes on its last frame until it is focused again. The engine notices a
	* window leaving this list and tells its application to stop rendering, so
	* the saving is real, not cosmetic. When nothing is focused the candidates
	* all stream: a session with no focus yet must not open on a wall of stills.
	*
	* `live` is the per-column opt-out of that one rule, and the only thing that
	* can widen the list: the windows of a focused column marked `Column.live`.
	* See [`liveWindows`], which is what a caller should pass. It cannot narrow
	* anything, so a window frozen with an empty `live` stays frozen with a full
	* one, and every id in it still has to clear the viewport filter above.
	*/
	function streamList(placed, output, config, focused, pauseInactive, fullscreen, live = []) {
		return placed.filter((w) => w.id === fullscreen || intersectsViewport(w.rect, output, config)).filter((w) => !pauseInactive || focused === null || w.id === focused || w.id === fullscreen || live.includes(w.id)).map((w) => w.id);
	}
	/**
	* The windows a live column adds to the stream list. See [`Column.live`].
	*
	* # A fitted workspace is live throughout
	*
	* Fitting puts every column on screen at once and stops the strip scrolling,
	* which is a statement that everything in it is meant to be watched: four
	* videos tiled into quadrants are four videos, not one video and three
	* stills. So fitting implies live for the whole workspace and there is no
	* second switch to find.
	*
	* That stays bounded for the same reason the mode does. Fitting only holds
	* what fits, and `streamList` still drops anything the viewport cannot show,
	* so a workspace with more columns than fit streams the ones on screen and no
	* more.
	*
	* Otherwise only the focused column is consulted, which is the whole reason
	* this is affordable: whatever the user has marked, at most one column can be
	* focused, so the extra encoder sessions are bounded by the tallest stack and
	* not by how liberally the flag has been handed out.
	*
	* A column of one is not a group, so its flag reads as nothing here. That
	* window is the focused one whenever the column is, and it therefore already
	* streams; honouring the flag would only mean this function could be used to
	* keep a single named window awake, which is exactly the per-window pause
	* control that was taken out of the windows panel. The flag is left on the
	* column rather than cleared, so a column that is stacked up again remembers
	* what it was told, the way it remembers its width.
	*/
	function liveWindows(state) {
		const ws = currentWorkspace(state);
		if (ws.fit) return ws.columns.flatMap((column) => column.windows);
		const column = ws.columns[clampIndex(ws.focus, ws.columns.length)];
		if (!column?.live || column.windows.length < 2) return [];
		return column.windows;
	}
	function withWorkspace(state, fn) {
		const index = clampIndex(state.focus, state.workspaces.length);
		const workspaces = state.workspaces.map((ws, i) => {
			if (i !== index) return ws;
			const next = fn(ws);
			const column = next.columns[clampIndex(next.focus, next.columns.length)];
			const focused = column?.windows[clampIndex(column.focus, column.windows.length)];
			return next.fullscreenOverride !== void 0 && next.fullscreenOverride !== focused ? {
				...next,
				fullscreenOverride: void 0
			} : next;
		});
		return {
			...state,
			workspaces
		};
	}
	/**
	* Keep exactly one trailing empty workspace, and drop any others.
	*
	* Without this, closing the last window on a middle workspace leaves a hole you
	* have to scroll past forever.
	*/
	function normaliseWorkspaces(state) {
		const nonEmpty = state.workspaces.filter((ws) => ws.columns.length > 0);
		const focused = state.workspaces[clampIndex(state.focus, state.workspaces.length)];
		const workspaces = [...nonEmpty, emptyWorkspace()];
		const kept = focused && focused.columns.length > 0 ? nonEmpty.indexOf(focused) : -1;
		return {
			workspaces,
			focus: clampIndex(kept >= 0 ? kept : clampIndex(state.focus, workspaces.length), workspaces.length)
		};
	}
	function scrollFocusIntoView(state, output, config) {
		const offset = targetOffset(state, output, config);
		const focused = focusedWindow(state);
		return withWorkspace(state, (ws) => ({
			...ws,
			viewOffset: offset,
			fullscreen: ws.fullscreen !== null && ws.fullscreen === focused ? ws.fullscreen : null
		}));
	}
	function settle(state, output, config) {
		return scrollFocusIntoView(normaliseWorkspaces(state), output, config);
	}
	/**
	* Add a window as a new column, immediately right of the focused one.
	*
	* niri inserts adjacent rather than appending, so a window you open while
	* reading something lands next to it instead of at the far end of the strip.
	*/
	function addWindow(state, id, output, config) {
		if (findWindow(state, id)) return state;
		return settle(withWorkspace(state, (ws) => {
			const at = ws.columns.length === 0 ? 0 : clampIndex(ws.focus, ws.columns.length) + 1;
			const columns = [...ws.columns];
			columns.splice(at, 0, {
				windows: [id],
				focus: 0,
				width: config.defaultWidth
			});
			return {
				...ws,
				columns,
				focus: at
			};
		}), output, config);
	}
	function removeWindow(state, id, output, config) {
		const found = findWindow(state, id);
		if (!found) return state;
		const workspaces = state.workspaces.map((ws, wsIndex) => {
			if (wsIndex !== found.workspace) return ws;
			const columns = ws.columns.map((column, colIndex) => {
				if (colIndex !== found.column) return column;
				const windows = column.windows.filter((w) => w !== id);
				const focus = found.row < column.focus ? column.focus - 1 : column.focus;
				return {
					...column,
					windows,
					focus: clampIndex(focus, windows.length)
				};
			}).filter((column) => column.windows.length > 0);
			let focus = ws.focus;
			if (ws.columns[found.column].windows.length === 1 && found.column < ws.focus) focus -= 1;
			return {
				...ws,
				columns,
				focus: clampIndex(focus, columns.length),
				fullscreenOverride: ws.fullscreenOverride === id ? void 0 : ws.fullscreenOverride
			};
		});
		return settle({
			...state,
			workspaces
		}, output, config);
	}
	function findWindow(state, id) {
		for (const [workspace, ws] of state.workspaces.entries()) for (const [column, col] of ws.columns.entries()) {
			const row = col.windows.indexOf(id);
			if (row !== -1) return {
				workspace,
				column,
				row
			};
		}
		return null;
	}
	/** The focused window, or null if the focused workspace is empty. */
	function focusedWindow(state) {
		const ws = currentWorkspace(state);
		const column = ws.columns[clampIndex(ws.focus, ws.columns.length)];
		if (!column) return null;
		return column.windows[clampIndex(column.focus, column.windows.length)] ?? null;
	}
	function focusWindow(state, id, output, config) {
		const found = findWindow(state, id);
		if (!found) return state;
		const workspaces = state.workspaces.map((ws, wsIndex) => wsIndex !== found.workspace ? ws : {
			...ws,
			focus: found.column,
			columns: ws.columns.map((column, colIndex) => colIndex === found.column ? {
				...column,
				focus: found.row
			} : column)
		});
		return scrollFocusIntoView({
			...state,
			workspaces,
			focus: found.workspace
		}, output, config);
	}
	function focusColumn(state, delta, output, config) {
		return scrollFocusIntoView(withWorkspace(state, (ws) => ({
			...ws,
			focus: clampIndex(ws.focus + delta, ws.columns.length)
		})), output, config);
	}
	var focusLeft = (s, o, c) => focusColumn(s, -1, o, c);
	var focusRight = (s, o, c) => focusColumn(s, 1, o, c);
	/** Move focus within the focused column's stack. */
	function focusRow(state, delta) {
		return withWorkspace(state, (ws) => ({
			...ws,
			columns: ws.columns.map((column, i) => i !== clampIndex(ws.focus, ws.columns.length) ? column : {
				...column,
				focus: clampIndex(column.focus + delta, column.windows.length)
			})
		}));
	}
	var focusUp = (s) => focusRow(s, -1);
	var focusDown = (s) => focusRow(s, 1);
	/** Cycle the focused column between the width presets. */
	function cycleWidth(state, output, config) {
		return scrollFocusIntoView(withWorkspace(state, (ws) => ({
			...ws,
			columns: ws.columns.map((column, i) => i !== clampIndex(ws.focus, ws.columns.length) ? column : {
				...column,
				width: (column.width + 1) % WIDTH_PRESETS.length
			})
		})), output, config);
	}
	/**
	* Set a named column's width outright.
	*
	* `cycleWidth` is the keyboard's operation: one key, one step, no way to name
	* a destination. A panel offering the presets as four buttons has a
	* destination, and reaching it by stepping would push a layout per step,
	* animating the column through every width in between on the way to the one
	* that was asked for.
	*
	* Named column rather than the focused one, so choosing a width for a window
	* in the list does not first have to focus it.
	*/
	function setColumnWidth(state, id, preset, output, config) {
		const where = findWindow(state, id);
		if (!where || where.workspace !== state.focus) return state;
		const width = clampIndex(preset, WIDTH_PRESETS.length);
		if (currentWorkspace(state).columns[where.column]?.width === width) return state;
		return scrollFocusIntoView(withWorkspace(state, (ws) => ({
			...ws,
			columns: ws.columns.map((column, i) => i === where.column ? {
				...column,
				width
			} : column)
		})), output, config);
	}
	/**
	* Mark a named window's column as streaming all of itself, or stop.
	*
	* Named rather than focused, and no re-settling afterwards, for the same
	* reasons as {@link setColumnWidth}: the control is a row in a list, so
	* choosing from it must not first move focus somewhere the user did not ask
	* for. Unlike a width this changes no geometry at all, so there is no offset
	* to re-derive and nothing to animate. Only the stream list changes, and the
	* caller re-sends that.
	*
	* Returns the same object when nothing would change, which is what stops a
	* toggle pressed twice from pushing two identical layouts at the engine.
	*/
	function setColumnLive(state, id, live) {
		const where = findWindow(state, id);
		if (!where || where.workspace !== state.focus) return state;
		const column = currentWorkspace(state).columns[where.column];
		if (!column || (column.live ?? false) === live) return state;
		return withWorkspace(state, (ws) => ({
			...ws,
			columns: ws.columns.map((c, i) => i === where.column ? {
				...c,
				live
			} : c)
		}));
	}
	/** Is the focused workspace showing a window fullscreen? */
	function isFullscreen(state) {
		return currentWorkspace(state).fullscreen !== null;
	}
	/** The window the focused workspace is showing fullscreen, if any. */
	function fullscreenWindow(state) {
		return currentWorkspace(state).fullscreen;
	}
	/**
	* Fill the viewport with the focused window, or go back to the strip.
	*
	* "Full viewport" means exactly that: the client's whole visible area, not the
	* widest preset. On a tablet that is the difference between a video with the
	* strip's gaps and neighbours around it and a video, so it deserves its own
	* control rather than being the last stop on a width cycle.
	*/
	/**
	* Put a named window fullscreen, or take it out, because it asked.
	*
	* Separate from `toggleFullscreen`, which acts on the focused window and flips
	* whatever state it is in. A client's request says both which window and which
	* direction, and honouring it as a toggle would turn a player asking to *enter*
	* fullscreen while already fullscreen into a request to leave.
	*
	* The window is focused as well. A video that has just filled the screen and
	* does not have the keyboard cannot be paused with the space bar, which is the
	* first thing anybody tries.
	*/
	function setFullscreen(state, id, fullscreen, output, config) {
		const where = findWindow(state, id);
		if (!where || where.workspace !== state.focus) return state;
		const workspace = currentWorkspace(state);
		if (workspace.fullscreenOverride === id) return state;
		if (workspace.fullscreen === id === fullscreen) return state;
		return scrollFocusIntoView(withWorkspace(fullscreen ? focusWindow(state, id, output, config) : state, (ws) => ({
			...ws,
			fullscreen: fullscreen ? id : ws.fullscreen === id ? null : ws.fullscreen
		})), output, config);
	}
	/**
	* Fit the focused workspace's columns to the screen, or go back to scrolling.
	*
	* Clears fullscreen on the way in. Fitting is a request to see everything at
	* once and fullscreen is a request to see one thing, so leaving it set would
	* mean pressing "fit to screen" and watching nothing happen, since `layout`
	* short-circuits on fullscreen before it reaches any of this.
	*
	* The offset is re-derived rather than assumed, because that is what turns
	* scrolling off going in and puts the strip back under the focused column
	* coming out.
	*/
	function setFit(state, fit, output, config) {
		if (currentWorkspace(state).fit === fit) return state;
		return scrollFocusIntoView(withWorkspace(state, (ws) => ({
			...ws,
			fit,
			fullscreen: fit ? null : ws.fullscreen,
			fullscreenOverride: fit ? void 0 : ws.fullscreenOverride
		})), output, config);
	}
	function toggleFullscreen(state, output, config) {
		const focused = focusedWindow(state);
		if (focused === null) return state;
		return scrollFocusIntoView(withWorkspace(state, (ws) => ({
			...ws,
			fullscreen: ws.fullscreen === focused ? null : focused,
			fullscreenOverride: focused
		})), output, config);
	}
	/**
	* Pull the focused window into the column on its left, stacking it.
	*
	* niri calls this "consume". It is how a stack gets built without a separate
	* mode: you open windows normally and merge the ones that belong together.
	*/
	function consumeIntoColumn(state, output, config) {
		const ws0 = currentWorkspace(state);
		if (clampIndex(ws0.focus, ws0.columns.length) === 0 || ws0.columns.length < 2) return state;
		return settle(withWorkspace(state, (ws) => {
			const at = clampIndex(ws.focus, ws.columns.length);
			const source = ws.columns[at];
			const id = source.windows[clampIndex(source.focus, source.windows.length)];
			if (id === void 0) return ws;
			const columns = ws.columns.map((column, i) => {
				if (i === at - 1) return {
					...column,
					windows: [...column.windows, id],
					focus: column.windows.length
				};
				if (i === at) {
					const windows = column.windows.filter((w) => w !== id);
					return {
						...column,
						windows,
						focus: clampIndex(column.focus, windows.length)
					};
				}
				return column;
			}).filter((column) => column.windows.length > 0);
			return {
				...ws,
				columns,
				focus: clampIndex(at - 1, columns.length)
			};
		}), output, config);
	}
	/**
	* Push the focused window out of its stack into a column of its own.
	*
	* The inverse of {@link consumeIntoColumn}. niri calls it "expel".
	*/
	function expelFromColumn(state, output, config) {
		const ws0 = currentWorkspace(state);
		const source0 = ws0.columns[clampIndex(ws0.focus, ws0.columns.length)];
		if (!source0 || source0.windows.length < 2) return state;
		return settle(withWorkspace(state, (ws) => {
			const at = clampIndex(ws.focus, ws.columns.length);
			const source = ws.columns[at];
			const id = source.windows[clampIndex(source.focus, source.windows.length)];
			if (id === void 0) return ws;
			const remaining = source.windows.filter((w) => w !== id);
			const columns = [...ws.columns];
			columns[at] = {
				...source,
				windows: remaining,
				focus: clampIndex(source.focus, remaining.length)
			};
			columns.splice(at + 1, 0, {
				windows: [id],
				focus: 0,
				width: source.width
			});
			return {
				...ws,
				columns,
				focus: at + 1
			};
		}), output, config);
	}
	/**
	* Move a window to a chosen place in the strip.
	*
	* The general form of `consumeIntoColumn` and `expelFromColumn`, which move
	* the focused window one step in a fixed direction. Those are right for a
	* keyboard, where there is nowhere to point. A drag knows exactly where it is
	* going, and expressing that as a run of consume and expel calls would make an
	* intermediate arrangement visible on every step and could not express "into
	* the third row of that column" at all.
	*
	* The moved window keeps focus, because you are looking at it and it is
	* inconceivable that moving something should focus something else.
	*/
	function moveWindow(state, id, target, output, config) {
		const where = findWindow(state, id);
		if (!where || where.workspace !== state.focus) return state;
		return settle(withWorkspace(withWorkspace(state, (ws) => {
			const emptied = ws.columns.map((column) => {
				if (!column.windows.includes(id)) return column;
				const windows = column.windows.filter((w) => w !== id);
				return {
					...column,
					windows,
					focus: clampIndex(column.focus, windows.length)
				};
			}).filter((column) => column.windows.length > 0);
			const width = ws.columns.find((column) => column.windows.includes(id))?.width ?? 0;
			if (target.kind === "newColumn") {
				const at = Math.max(0, Math.min(target.index, emptied.length));
				const columns = [...emptied];
				columns.splice(at, 0, {
					windows: [id],
					focus: 0,
					width
				});
				return {
					...ws,
					columns,
					focus: at
				};
			}
			if (emptied.length === 0) return {
				...ws,
				columns: [{
					windows: [id],
					focus: 0,
					width
				}],
				focus: 0
			};
			const at = clampIndex(target.index, emptied.length);
			const column = emptied[at];
			const row = target.row === void 0 ? column.windows.length : Math.max(0, Math.min(target.row, column.windows.length));
			const windows = [...column.windows];
			windows.splice(row, 0, id);
			const columns = [...emptied];
			columns[at] = {
				...column,
				windows,
				focus: row
			};
			return {
				...ws,
				columns,
				focus: at
			};
		}), (ws) => ({
			...ws,
			fullscreen: null,
			fullscreenOverride: void 0
		})), output, config);
	}
	/** Switch workspace. Clamped, and the trailing empty one is always reachable. */
	function focusWorkspace(state, delta, output, config) {
		const focus = clampIndex(state.focus + delta, state.workspaces.length);
		return scrollFocusIntoView({
			...state,
			focus
		}, output, config);
	}
	/**
	* Move the focused window to another workspace, following it there.
	*
	* Done in one step rather than as remove-then-add. Removing normalises the
	* workspace list, and if that collapses the workspace being left, every later
	* index shifts and the window lands back where it started.
	*/
	function moveToWorkspace(state, delta, output, config) {
		const id = focusedWindow(state);
		if (id === null) return state;
		const from = clampIndex(state.focus, state.workspaces.length);
		const to = clampIndex(from + delta, state.workspaces.length);
		if (to === from) return state;
		const workspaces = state.workspaces.map((ws, index) => {
			if (index === from) return detach(ws, id);
			if (index === to) return attach(ws, id, config);
			return ws;
		});
		const moved = normaliseWorkspaces({
			...state,
			workspaces,
			focus: to
		});
		const landed = findWindow(moved, id);
		return scrollFocusIntoView(landed ? {
			...moved,
			focus: landed.workspace
		} : moved, output, config);
	}
	/**
	* Send a named window to a named workspace, and stay where you are.
	*
	* Two differences from `moveToWorkspace`, both deliberate.
	*
	* It names the window rather than acting on the focused one, because a drag
	* knows what it picked up and focusing something first just to move it would
	* be a visible flicker on the way to somewhere else.
	*
	* It does not follow the window. `moveToWorkspace` is a keyboard command, and
	* a keyboard has no way to say "and now show me that"; following is the only
	* way to see what happened. A drag onto a workspace chip is the opposite: you
	* are tidying, and being thrown onto another workspace on every flick would
	* make organising three windows into three separate journeys back.
	*/
	function sendToWorkspace(state, id, index, output, config) {
		const from = findWindow(state, id);
		if (!from) return state;
		const to = clampIndex(index, state.workspaces.length);
		if (to === from.workspace) return state;
		const workspaces = state.workspaces.map((ws, at) => {
			if (at === from.workspace) return detach(ws, id);
			if (at === to) return attach(ws, id, config);
			return ws;
		});
		const staying = state.workspaces[clampIndex(state.focus, state.workspaces.length)];
		const moved = normaliseWorkspaces({
			...state,
			workspaces,
			focus: state.focus
		});
		const stillThere = staying ? moved.workspaces.indexOf(staying) : -1;
		return scrollFocusIntoView(stillThere === -1 ? moved : {
			...moved,
			focus: stillThere
		}, output, config);
	}
	/** Remove a window from a workspace, dropping any column it empties. */
	function detach(ws, id) {
		const columns = ws.columns.map((column) => {
			if (!column.windows.includes(id)) return column;
			const windows = column.windows.filter((w) => w !== id);
			return {
				...column,
				windows,
				focus: clampIndex(column.focus, windows.length)
			};
		}).filter((column) => column.windows.length > 0);
		return {
			...ws,
			columns,
			focus: clampIndex(ws.focus, columns.length),
			fullscreenOverride: ws.fullscreenOverride === id ? void 0 : ws.fullscreenOverride
		};
	}
	/** Add a window to a workspace as a new column beside its focus. */
	function attach(ws, id, config) {
		const at = ws.columns.length === 0 ? 0 : clampIndex(ws.focus, ws.columns.length) + 1;
		const columns = [...ws.columns];
		columns.splice(at, 0, {
			windows: [id],
			focus: 0,
			width: config.defaultWidth
		});
		return {
			...ws,
			columns,
			focus: at,
			fullscreenOverride: void 0
		};
	}
	/**
	* Re-derive the offset after the viewport changes.
	*
	* Column widths are fractions of the viewport, so they do change on resize.
	* What must not change is which windows exist, their order, or their stacking.
	*/
	function reflow(state, output, config) {
		return scrollFocusIntoView(state, output, config);
	}
	/** Every window in the whole strip, across all workspaces. */
	function allWindows(state) {
		return state.workspaces.flatMap((ws) => ws.columns.flatMap((c) => c.windows));
	}
	//#endregion
	//#region packages/shell/src/lib/arrangement.ts
	var KEY = "lwfa.arrangement.v1";
	function validState(value) {
		if (!value || typeof value !== "object") return false;
		const state = value;
		const index = (n, length) => Number.isInteger(n) && Number(n) >= 0 && Number(n) < Math.max(1, length);
		if (!Array.isArray(state.workspaces) || state.workspaces.length === 0 || !index(state.focus, state.workspaces.length)) return false;
		const ids = /* @__PURE__ */ new Set();
		return state.workspaces.every((ws) => {
			if (!ws || !Array.isArray(ws.columns) || !index(ws.focus, ws.columns.length) || !Number.isFinite(ws.viewOffset) || typeof ws.fit !== "boolean" || !(ws.fullscreen === null || Number.isInteger(ws.fullscreen)) || !(ws.fullscreenOverride === void 0 || Number.isInteger(ws.fullscreenOverride))) return false;
			if (!ws.columns.every((column) => {
				if (!column || !Array.isArray(column.windows) || column.windows.length === 0 || !index(column.focus, column.windows.length) || !index(column.width, WIDTH_PRESETS.length) || !(column.live === void 0 || typeof column.live === "boolean")) return false;
				return column.windows.every((id) => {
					if (!Number.isSafeInteger(id) || id < 0 || ids.has(id)) return false;
					ids.add(id);
					return true;
				});
			})) return false;
			if (ws.fullscreenOverride !== void 0 && ws.columns[ws.focus]?.windows[ws.columns[ws.focus].focus] !== ws.fullscreenOverride) return false;
			return ws.fullscreen === null || ws.columns.some((column) => column.windows.includes(ws.fullscreen));
		});
	}
	function loadArrangement() {
		try {
			const value = JSON.parse(globalThis.sessionStorage?.getItem(KEY) ?? "null");
			if (value && validState(value.state) && Number.isFinite(value.output?.width) && Number.isFinite(value.output?.height) && value.output.width > 0 && value.output.height > 0) return value;
		} catch {}
		return null;
	}
	/** Reconcile a browser arrangement with the engine's current windows. */
	function restoreArrangement(windows, focused, output, config, saved, current) {
		const live = new Set(windows.map((w) => w.id));
		const comparable = (items) => items.filter((item) => live.has(item.id)).map(({ id, rect, z }) => [
			id,
			rect.x,
			rect.y,
			rect.width,
			rect.height,
			z
		]).sort((a, b) => a[0] - b[0]);
		if (saved && current && current.length > 0 && saved.output.width === output.width && saved.output.height === output.height && JSON.stringify(comparable(layout(saved.state, output, config))) === JSON.stringify(comparable(current))) {
			let next = saved.state;
			for (const id of allWindows(next)) if (!live.has(id)) next = removeWindow(next, id, output, config);
			for (const w of windows) next = addWindow(next, w.id, output, config);
			if (focused !== null && focusedWindow(next) !== focused) next = focusWindow(next, focused, output, config);
			return next;
		}
		let next = windows.reduce((state, w) => addWindow(state, w.id, output, config), EMPTY);
		if (focused !== null) next = focusWindow(next, focused, output, config);
		for (const w of windows) if (w.fullscreen) next = setFullscreen(next, w.id, true, output, config);
		return next;
	}
	//#endregion
	//#region clients/ios/LayoutBridge.ts
	var state = EMPTY;
	var output = {
		width: 1,
		height: 1
	};
	var config = DEFAULT_CONFIG;
	var initialized = false;
	var saved = null;
	var aliases = /* @__PURE__ */ new Map();
	var originals = /* @__PURE__ */ new Map();
	var nextAlias = 1;
	function alias(value) {
		if (typeof value !== "string" || !/^(0|[1-9][0-9]*)$/.test(value) || BigInt(value) > 18446744073709551615n) throw Error("Invalid window identifier");
		let id = aliases.get(value);
		if (id === void 0) {
			if (!Number.isSafeInteger(nextAlias)) throw Error("Window identifier capacity exceeded");
			id = nextAlias++;
			aliases.set(value, id);
			originals.set(id, value);
		}
		return id;
	}
	function original(id) {
		if (id == null) return null;
		const value = originals.get(id);
		if (value === void 0) throw Error("Unknown window identifier");
		return value;
	}
	function externalState() {
		return {
			...state,
			workspaces: state.workspaces.map((ws) => ({
				...ws,
				fullscreen: original(ws.fullscreen),
				...ws.fullscreenOverride === void 0 ? {} : { fullscreenOverride: original(ws.fullscreenOverride) },
				columns: ws.columns.map((column) => ({
					...column,
					windows: column.windows.map(original)
				}))
			}))
		};
	}
	function snapshot() {
		const placed = layout(state, output, config);
		const streams = (pause) => streamList(placed, output, config, focusedWindow(state), pause, fullscreenWindow(state), liveWindows(state)).map(original);
		return {
			state: externalState(),
			focused: original(focusedWindow(state)),
			fullscreen: isFullscreen(state),
			placed: placed.map((w) => ({
				...w,
				id: original(w.id)
			})),
			streams: streams(false),
			activeStreams: streams(true),
			presets: WIDTH_PRESETS,
			spring: WINDOW_SPRING,
			config,
			output,
			saved: {
				state,
				output,
				aliases: [...aliases]
			}
		};
	}
	function restore(value) {
		Object.defineProperty(globalThis, "sessionStorage", {
			configurable: true,
			value: { getItem: () => JSON.stringify(value) }
		});
		const candidate = loadArrangement();
		delete globalThis.sessionStorage;
		if (!candidate || !Array.isArray(value.aliases)) return;
		const pairs = value.aliases;
		const restored = /* @__PURE__ */ new Map();
		const reverse = /* @__PURE__ */ new Map();
		for (const pair of pairs) {
			if (!Array.isArray(pair) || pair.length !== 2) return;
			const [key, id] = pair;
			if (typeof key !== "string" || !/^(0|[1-9][0-9]*)$/.test(key) || BigInt(key) > 18446744073709551615n || !Number.isSafeInteger(id) || id < 1 || id >= Number.MAX_SAFE_INTEGER || restored.has(key) || reverse.has(id)) return;
			restored.set(key, id);
			reverse.set(id, key);
		}
		if (allWindows(candidate.state).some((id) => !reverse.has(id))) return;
		aliases = restored;
		originals = reverse;
		nextAlias = Math.max(0, ...reverse.keys()) + 1;
		saved = candidate;
	}
	function dimensions(value) {
		if (!Number.isFinite(value?.width) || !Number.isFinite(value?.height) || value.width < 1 || value.height < 1) throw Error("Invalid canvas dimensions");
		output = {
			width: value.width,
			height: value.height
		};
	}
	function action(name, args) {
		const n = (index) => {
			const value = Number(args[index]);
			if (!Number.isSafeInteger(value)) throw Error("Invalid layout index");
			return value;
		};
		const id = () => alias(args[0]);
		switch (name) {
			case "focus":
				state = focusWindow(state, id(), output, config);
				break;
			case "focusLeft":
				state = focusLeft(state, output, config);
				break;
			case "focusRight":
				state = focusRight(state, output, config);
				break;
			case "focusUp":
				state = focusUp(state);
				break;
			case "focusDown":
				state = focusDown(state);
				break;
			case "cycleWidth":
				state = cycleWidth(state, output, config);
				break;
			case "width":
				state = setColumnWidth(state, id(), n(1), output, config);
				break;
			case "live":
				state = setColumnLive(state, id(), args[1] === true);
				break;
			case "fullscreen":
				state = toggleFullscreen(state, output, config);
				break;
			case "fullscreenRequest":
				state = setFullscreen(state, id(), args[1] === true, output, config);
				break;
			case "fit":
				state = setFit(state, args[0] === true, output, config);
				break;
			case "stack":
				state = consumeIntoColumn(state, output, config);
				break;
			case "unstack":
				state = expelFromColumn(state, output, config);
				break;
			case "workspace":
				state = focusWorkspace(state, n(0) - state.focus, output, config);
				break;
			case "moveWorkspace":
				state = moveToWorkspace(state, n(0), output, config);
				break;
			case "sendWorkspace":
				state = sendToWorkspace(state, id(), n(1), output, config);
				break;
			case "move": {
				const target = args[1];
				if (!target || !["column", "newColumn"].includes(target.kind) || !Number.isSafeInteger(Number(target.index)) || Number(target.index) < 0) throw Error("Invalid move target");
				const row = target.row == null ? void 0 : Number(target.row);
				if (row !== void 0 && (!Number.isSafeInteger(row) || row < 0)) throw Error("Invalid row");
				state = moveWindow(state, id(), {
					kind: target.kind,
					index: Number(target.index),
					row
				}, output, config);
				break;
			}
			default: throw Error(`Unknown layout action: ${name}`);
		}
	}
	function dispatch(json) {
		try {
			const message = JSON.parse(json);
			switch (message.type) {
				case "reset":
					state = EMPTY;
					initialized = false;
					saved = null;
					aliases.clear();
					originals.clear();
					nextAlias = 1;
					if (message.saved) restore(message.saved);
					break;
				case "configure":
					config = configFrom({
						orientation: ["horizontal", "vertical"].includes(message.orientation) ? message.orientation : "auto",
						defaultWidth: message.defaultWidth,
						centreFocused: message.centreFocused === true
					});
					state = reflow(state, output, config);
					break;
				case "resize":
					dimensions(message.output);
					state = reflow(state, output, config);
					break;
				case "reconcile": {
					dimensions(message.output);
					const windows = message.windows.map((w) => ({
						...w,
						id: alias(w.id)
					}));
					const focused = message.focused == null ? null : alias(message.focused);
					const current = (message.current ?? []).map((w) => ({
						...w,
						id: alias(w.id)
					}));
					if (!initialized) {
						state = restoreArrangement(windows, focused, output, config, saved, current);
						initialized = true;
						saved = null;
					} else {
						const live = new Set(windows.map((w) => w.id));
						for (const id of allWindows(state)) if (!live.has(id)) state = removeWindow(state, id, output, config);
						for (const w of windows) state = addWindow(state, w.id, output, config);
						if (focused !== null && focusedWindow(state) !== focused) state = focusWindow(state, focused, output, config);
						state = reflow(state, output, config);
					}
					break;
				}
				case "action":
					action(message.name, message.args ?? []);
					break;
				case "snapshot": break;
				default: throw Error("Unknown layout message");
			}
			return JSON.stringify(snapshot());
		} catch (error) {
			return JSON.stringify({ error: String(error) });
		}
	}
	//#endregion
	exports.dispatch = dispatch;
	return exports;
})({});
