/**
 * The shell protocol, TypeScript side.
 *
 * Mirrors `crates/lwfa-proto`. Read that crate's module docs for the design;
 * this file is the wire mapping and a strict runtime decoder.
 *
 * # Why a runtime decoder and not just types
 *
 * TypeScript types vanish at runtime, so `JSON.parse(...) as ToShell` asserts
 * nothing. If the engine renamed `appId` and this side did not, the field would
 * quietly read `undefined` and windows would lose their names with no error
 * anywhere. The decoders below check the shape for real, and
 * `test/parity.test.ts` runs them against fixtures generated by the Rust
 * implementation.
 *
 * Decoding is strict about unknown fields, matching `deny_unknown_fields` on
 * the Rust side. Protocol evolution goes through {@link PROTOCOL_VERSION}, not
 * through silently tolerated extra keys.
 */

/** Bumped on any breaking change. Must equal the Rust `PROTOCOL_VERSION`. */
export const PROTOCOL_VERSION = 0

/** Engine-assigned window handle. A bare number on the wire. */
export type WindowId = number

export interface Output {
  width: number
  height: number
  scale: number
}

export interface Rect {
  x: number
  y: number
  width: number
  height: number
}

export interface WindowInfo {
  id: WindowId
  appId: string | null
  title: string | null
}

export interface SpringSpec {
  stiffness: number
  damping: number
  mass: number
}

export interface Animation {
  spring: SpringSpec
}

export interface WindowLayout {
  id: WindowId
  rect: Rect
  z: number
}

/**
 * A pointer button, Linux evdev numbering (`BTN_LEFT` = 0x110).
 * Not the browser's 0/1/2, which is a different numbering entirely.
 */
export type ButtonCode = number

/**
 * A key, Linux evdev numbering (`KEY_A` = 30).
 *
 * Derived from `KeyboardEvent.code` (the physical key), never from
 * `KeyboardEvent.key` (the character), or the layout would be applied twice.
 * See `packages/shell/src/input.ts`.
 */
export type KeyCode = number

/** Keyboard modifier state at the time of a key press. */
export interface Modifiers {
  alt: boolean
  ctrl: boolean
  shift: boolean
  /** The Super/Windows/Command key. */
  logo: boolean
}

export type ToShell =
  | {
      type: "hello"
      protocolVersion: number
      output: Output
      windows: WindowInfo[]
      focused: WindowId | null
      permissions: Permissions
      /** Which account this is. "owner" for AUTH_PASS. */
      account: string
      /** This connection's own id, so it can recognise itself in `peers`. */
      session: SessionId
      /**
       * Whether this connection is the one driving layout. See `role`.
       */
      primary: boolean
      /** Everyone connected right now, including this session. */
      peers: PeerInfo[]
    }
  | { type: "outputChanged"; output: Output }
  /**
   * Whether this connection is now the one driving layout.
   *
   * # Why there is a "driving" connection at all
   *
   * Several devices can watch and use one session, but a window has exactly one
   * size, so there is exactly one arrangement. Letting every connection push
   * its own would make two tablets fight over every window, each resizing what
   * the other just placed. So one connection owns layout and the rest follow
   * it, and any of them can ask to take over.
   *
   * A connection that is not primary still sends input, still asks for the
   * streams it needs, and still gets every frame. It just does not decide where
   * windows go; it is told, with `layout`.
   */
  | { type: "role"; primary: boolean }
  /**
   * The arrangement the primary connection chose, for everyone else.
   *
   * In the engine's output coordinates. A follower fits these into whatever
   * viewport it has rather than recomputing them, because recomputing would
   * produce a different arrangement for a window that can only have one.
   */
  | { type: "layout"; windows: WindowLayout[]; output: Output }
  /** Who is connected. Sent whenever that changes. */
  | { type: "peers"; peers: PeerInfo[] }
  | { type: "windowOpened"; window: WindowInfo }
  | { type: "windowChanged"; window: WindowInfo }
  | { type: "windowClosed"; id: WindowId }
  | { type: "focusChanged"; id: WindowId | null }
  /**
   * A modified key the engine did not claim for itself.
   *
   * "Focus the column to the left" is layout policy, so it belongs to the
   * shell. `key` is an xkb keysym name such as `"h"`, `"Left"` or `"Return"`.
   */
  | { type: "keyBinding"; key: string; modifiers: Modifiers }
  /**
   * Installed applications, in reply to `listApps`.
   *
   * On request rather than in `hello`, because scanning the desktop entries
   * touches the filesystem and most sessions never open the launcher.
   */
  | { type: "apps"; apps: AppEntry[] }
  /**
   * Icons for the applications, sent after `apps`.
   *
   * Separate so the launcher paints its list immediately and fills icons in as
   * they arrive.
   */
  | { type: "appIcons"; icons: AppIcon[] }
  /** The accounts on this machine. Never contains a password or a hash. */
  | { type: "accounts"; accounts: AccountInfo[] }
  /**
   * A request with a visible result did not happen, and why.
   *
   * Distinct from a dropped message: this exists so the UI can say "that name
   * is taken" rather than leaving a dialog waiting for a reply.
   */
  | { type: "error"; request: string; message: string }
  /**
   * The application asked for is already running outside this session.
   *
   * Applications that key "one instance" on their profile directory hand the
   * request to the copy that is already running, which opens a window wherever
   * it is. lwfa being a second session for the same user, that is the other
   * screen, and the launch looks like it did nothing.
   */
  /**
   * A window is asking to be fullscreen, or asking to stop.
   *
   * Sent when the client asks, which is what the fullscreen button inside a
   * video player does. The engine cannot grant it alone: the shell owns the
   * arrangement and would put the window back at its column width on the next
   * layout.
   */
  | { type: "fullscreenRequest"; window: WindowId; fullscreen: boolean }
  | {
      type: "alreadyRunning"
      command: string
      terminal: boolean
      program: string
      pid: number
    }
  /**
   * An application on the desktop opened a file dialog.
   *
   * The engine is the machine's file-chooser portal backend, so "upload a
   * file" inside a portal-aware app lands here instead of drawing a dialog
   * on a screen nobody is sitting at. Answered with `fileChosen` (machine
   * paths, uploads from this device, or both) or `fileCancel`.
   */
  | {
      type: "fileChooser"
      /** Correlates every message about this dialog. Engine-issued. */
      request: number
      /** Saving rather than opening: the one path returned need not exist. */
      save: boolean
      multiple: boolean
      /** The application wants a directory, not a file. */
      directory: boolean
      /** The application's own words for the dialog, shown verbatim. */
      title: string
      /** For saves: the filename the application suggests. */
      suggestedName: string | null
    }
  /** One directory of the machine, in reply to `listDir`. */
  | {
      type: "dirListing"
      request: number
      /** Canonicalised, so the browser can render and climb it honestly. */
      path: string
      entries: DirEntry[]
      error: string | null
    }
  /** An upload from this device landed (or failed) on the machine. */
  | { type: "uploaded"; request: number; name: string; ok: boolean }

/** One entry of a directory listing, for the file dialog's browser. */
export interface DirEntry {
  name: string
  /** A directory, so the browser descends instead of choosing. */
  dir: boolean
  /** Bytes, for files. Zero for directories. */
  size: number
}

/**
 * A video codec the engine can encode and a client might decode.
 *
 * Ordered best first in `PREFERENCE` on the shell side. HEVC is roughly a
 * third fewer bits than H.264 for the same picture.
 */
export type Codec = "hevc" | "h264"

/**
 * What a connected session is allowed to do.
 *
 * Advisory here: the shell uses it to grey out what it cannot use. The engine
 * enforces it. A permission checked only in the browser is not a permission,
 * it is a suggestion.
 */
export interface Permissions {
  mode: SessionMode
  /** Desktop entry ids this session may launch. `null` means all of them. */
  allowedApps: string[] | null
}

export type SessionMode = "view" | "interact"

/** Identifies one connection for the life of that connection. */
export type SessionId = number

/** One connected session, as shown to the others. */
export interface PeerInfo {
  id: SessionId
  /** Which account it authenticated as. "owner" for AUTH_PASS. */
  account: string
  mode: SessionMode
  /** Whether this is the connection currently driving layout. */
  primary: boolean
  /** Best-effort description of the device, from its user agent. */
  device: string
}

/** One resolved application icon, as a `data:` URI. */
export interface AppIcon {
  /** The desktop entry id this belongs to. */
  id: string
  /** `data:image/svg+xml;base64,...` or `data:image/png;base64,...`. */
  data: string
}

/** One account, as the Access panel sees it. */
export interface AccountInfo {
  id: number
  name: string
  permissions: Permissions
}

/** One launchable application, from a freedesktop `.desktop` entry. */
export interface AppEntry {
  /** The desktop file's basename without its extension. */
  id: string
  name: string
  description: string | null
  /** `Exec=`, with the freedesktop field codes (%f, %U, ...) removed. */
  exec: string
  /** An icon *name*, not a path. The shell has no icon theme; this is a hint. */
  icon: string | null
  categories: string[]
  terminal: boolean
}

export type ToEngine =
  | { type: "setLayout"; windows: WindowLayout[]; animate: Animation | null }
  | { type: "focusWindow"; id: WindowId }
  | { type: "closeWindow"; id: WindowId }
  /**
   * Launch a command line.
   *
   * `terminal` mirrors the desktop entry's `Terminal=true`: the program writes
   * to a tty and has no window, so the engine wraps it in one.
   */
  | { type: "spawn"; command: string; terminal: boolean }
  /**
   * Close a program running outside this session, then launch it in here.
   *
   * Only ever sent after somebody has been asked. `force` is the second
   * attempt: the polite request is answered by a save dialog on a screen
   * nobody is looking at.
   */
  | {
      type: "closeAndSpawn"
      command: string
      terminal: boolean
      pid: number
      force: boolean
    }
  /**
   * Tell the engine how much room the shell actually has, in CSS pixels.
   *
   * The engine resizes its output to match rather than the shell scaling a
   * fixed-size desktop down: scaling letterboxes, wastes the viewport, and
   * makes every window the wrong physical size. Answered with `outputChanged`.
   */
  | { type: "setViewport"; width: number; height: number; scale: number }
  /** Ask for the installed applications. Answered with `apps`, without icons. */
  | { type: "listApps" }
  /**
   * Ask for icons, by desktop entry id.
   *
   * Separate from `listApps` so the shell asks only for what it does not
   * already have cached. A full set is over a megabyte.
   */
  | { type: "requestIcons"; ids: string[] }
  /** Account administration. All four require the owner. */
  | { type: "listAccounts" }
  | { type: "createAccount"; name: string; password: string; permissions: Permissions }
  | { type: "updateAccount"; id: number; permissions: Permissions; password: string | null }
  | { type: "deleteAccount"; id: number }
  /**
   * Which windows the shell wants pixels for. Total: anything not listed stops
   * streaming. A shell compositing natively asks for none.
   */
  /**
   * Which windows to stream, and whether this client can decode H.264.
   *
   * An empty `codecs` is not hypothetical: WebCodecs `VideoDecoder` is only
   * exposed in a secure context, so a browser reached over plain HTTP on a LAN
   * address has no H.264 decoder while the same browser on localhost does.
   */
  | { type: "setStreams"; windows: WindowId[]; codecs: Codec[] }
  /**
   * Pointer moved within a window. Coordinates are window-relative logical
   * pixels, because during an animation the engine's actual window position
   * differs from the shell's target and output-relative coordinates would land
   * clicks where the window is heading rather than where it is.
   */
  | { type: "pointerMotion"; window: WindowId; x: number; y: number }
  | { type: "pointerButton"; button: ButtonCode; pressed: boolean }
  | { type: "pointerAxis"; horizontal: number; vertical: number }
  | { type: "pointerLeave" }
  | { type: "key"; key: KeyCode; pressed: boolean }
  /** Touch is first-class, not synthesised into pointer events. */
  | { type: "touchDown"; window: WindowId; id: number; x: number; y: number }
  | { type: "touchMotion"; window: WindowId; id: number; x: number; y: number }
  | { type: "touchUp"; id: number }
  /**
   * Ask to become the connection that drives layout.
   *
   * Granted to any session that may interact. Taking control is deliberately
   * not a negotiation: whoever asks last is the one holding the device the user
   * is looking at, and a prompt on the other device would be answered by nobody
   * when that device is a tablet on a table in another room.
   */
  | { type: "takeControl" }
  /**
   * Disconnect another session. The owner's alone.
   *
   * Kicks the connection, not the account: whoever it was can log back in.
   */
  | { type: "endSession"; session: SessionId }
  /**
   * Change what a live session may do, without touching its account.
   *
   * For handing someone your desktop to look at and taking the keys back
   * while they stay connected. Lasts only as long as the connection.
   */
  | { type: "setSessionMode"; session: SessionId; mode: SessionMode }
  /**
   * Attach or detach the session's virtual game controller.
   *
   * The device the engine creates is visible to the whole machine, which is
   * what makes Steam and SDL find it, so it exists only while a client is
   * actually using the pad.
   */
  | { type: "setGamepad"; enabled: boolean }
  /** A controller button, by W3C standard-mapping index. */
  | { type: "gamepadButton"; button: number; pressed: boolean }
  /** A controller axis. Sticks run -1 to 1, triggers 0 to 1. */
  | { type: "gamepadAxis"; axis: number; value: number }
  /**
   * Whether this connection wants to hear the machine.
   *
   * Per connection and off until asked for, like streams. Capturing costs a
   * process and about 1.5 Mbit/s per listener, so nobody pays for it until
   * somebody is listening.
   */
  | {
      type: "setAudio"
      /** Whether this connection wants to hear the machine. */
      enabled: boolean
      /**
       * Whether this connection can decode Opus.
       *
       * `AudioDecoder` is secure-context only, so a page on plain HTTP cannot,
       * however new the browser. One capture is fanned out to everyone, so it
       * is compressed only when every listener can take it.
       */
      opus: boolean
      /**
       * Whether the machine should also play the session's audio aloud.
       *
       * Machine-wide, not per connection: there is one set of speakers.
       */
      local: boolean
      /**
       * How many bits the sound deserves.
       *
       * One capture is fanned out to everyone, so the lowest request among
       * the listeners wins. "auto" follows the same budget the video adapts
       * on: sound degrades last, because broken audio is more jarring than a
       * softer picture.
       */
      quality: AudioQuality
    }
  /**
   * Start or stop feeding this session's microphone to the desktop.
   *
   * The audio itself travels as binary WebSocket messages tagged with
   * `MIC_TAG_OPUS` or `MIC_TAG_PCM`; this message is the consent and the
   * lifecycle. The engine plugs a machine-visible "lwfa Microphone" in while
   * a session feeds it and unplugs it after, so an idle session never leaves
   * a phantom microphone on the machine.
   */
  | { type: "setMic"; enabled: boolean }
  /**
   * Start or stop feeding this session's camera to the desktop. Mirrors
   * `setMic` exactly; frames travel as binary messages tagged `CAM_TAG`.
   */
  | { type: "setCamera"; enabled: boolean }
  /**
   * Ask for one directory of the machine, for the file dialog's browser.
   * Only meaningful while a `fileChooser` request is open.
   */
  | { type: "listDir"; request: number; path: string }
  /**
   * Announce one file about to be uploaded from this device. The bytes
   * follow as binary messages tagged `FILE_TAG`; `fileUploadDone` closes
   * the transfer. One file at a time per request, in the order announced.
   */
  | { type: "fileUpload"; request: number; name: string; size: number }
  | { type: "fileUploadDone"; request: number }
  /**
   * Answer a `fileChooser`: these machine paths, plus every file uploaded
   * under the request.
   */
  | { type: "fileChosen"; request: number; paths: string[] }
  /** Dismissed. Uploads already received under the request are discarded. */
  | { type: "fileCancel"; request: number }

/** How many bits the session's sound deserves. See `setAudio`. */
export type AudioQuality = "auto" | "high" | "medium" | "low"

/**
 * Leading byte of a binary uplink message: one 20ms Opus packet of
 * microphone audio, 48kHz mono. See the Rust `MIC_TAG_OPUS`.
 */
export const MIC_TAG_OPUS = 0x01

/** Same, but signed 16-bit little-endian PCM, 48kHz mono: the fallback for
 * a browser whose `AudioEncoder` cannot produce Opus. */
export const MIC_TAG_PCM = 0x02

/**
 * Leading byte of a binary uplink message carrying file-upload bytes: the
 * tag, the request id as a little-endian u64, then the chunk. See the Rust
 * `FILE_TAG`.
 */
export const FILE_TAG = 0x03

/**
 * Leading byte of a binary uplink message carrying one encoded camera
 * frame: H.264 Annex-B, self-describing, so the tag is the whole header.
 */
export const CAM_TAG = 0x04

/** Motion's defaults, matching `SpringSpec::default` on the Rust side. */
export const DEFAULT_SPRING: SpringSpec = { stiffness: 100, damping: 10, mass: 1 }

export class ProtocolError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "ProtocolError"
  }
}

// ---------------------------------------------------------------------------
// Strict field readers
//
// Hand-rolled rather than pulled from a validation library: the shell ships to
// a phone over a mobile connection, this is the only place that needs it, and
// being explicit about rejecting unknown keys is the entire point.
// ---------------------------------------------------------------------------

type Obj = Record<string, unknown>

function asObject(value: unknown, at: string): Obj {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new ProtocolError(`${at}: expected an object, got ${describe(value)}`)
  }
  return value as Obj
}

function describe(value: unknown): string {
  if (value === null) return "null"
  if (Array.isArray(value)) return "an array"
  return typeof value
}

/** Reject any key the schema does not name, mirroring `deny_unknown_fields`. */
function noExtraKeys(obj: Obj, allowed: readonly string[], at: string): void {
  for (const key of Object.keys(obj)) {
    if (!allowed.includes(key)) {
      throw new ProtocolError(
        `${at}: unknown field ${JSON.stringify(key)}, expected one of ${allowed.join(", ")}`,
      )
    }
  }
}

function num(obj: Obj, key: string, at: string): number {
  const v = obj[key]
  if (typeof v !== "number" || !Number.isFinite(v)) {
    throw new ProtocolError(`${at}.${key}: expected a finite number, got ${describe(v)}`)
  }
  return v
}

function int(obj: Obj, key: string, at: string): number {
  const v = num(obj, key, at)
  if (!Number.isInteger(v)) {
    throw new ProtocolError(`${at}.${key}: expected an integer, got ${v}`)
  }
  return v
}

function str(obj: Obj, key: string, at: string): string {
  const v = obj[key]
  if (typeof v !== "string") {
    throw new ProtocolError(`${at}.${key}: expected a string, got ${describe(v)}`)
  }
  return v
}

/**
 * Rust `Option<T>` serialises to `null`, never to an absent key, so a missing
 * key is a real error rather than an implicit None.
 */
function nullableStr(obj: Obj, key: string, at: string): string | null {
  const v = obj[key]
  if (v === null) return null
  if (typeof v !== "string") {
    throw new ProtocolError(`${at}.${key}: expected a string or null, got ${describe(v)}`)
  }
  return v
}

function nullableId(obj: Obj, key: string, at: string): WindowId | null {
  const v = obj[key]
  if (v === null) return null
  return int(obj, key, at)
}

function array(obj: Obj, key: string, at: string): unknown[] {
  const v = obj[key]
  if (!Array.isArray(v)) {
    throw new ProtocolError(`${at}.${key}: expected an array, got ${describe(v)}`)
  }
  return v
}

function tag(obj: Obj, at: string): string {
  const v = obj["type"]
  if (typeof v !== "string") {
    throw new ProtocolError(`${at}: missing discriminant "type"`)
  }
  return v
}

// ---------------------------------------------------------------------------
// Component decoders
// ---------------------------------------------------------------------------

function decodeOutput(value: unknown, at: string): Output {
  const o = asObject(value, at)
  noExtraKeys(o, ["width", "height", "scale"], at)
  return { width: int(o, "width", at), height: int(o, "height", at), scale: num(o, "scale", at) }
}

function decodeRect(value: unknown, at: string): Rect {
  const o = asObject(value, at)
  noExtraKeys(o, ["x", "y", "width", "height"], at)
  return {
    x: num(o, "x", at),
    y: num(o, "y", at),
    width: num(o, "width", at),
    height: num(o, "height", at),
  }
}

function decodeWindowInfo(value: unknown, at: string): WindowInfo {
  const o = asObject(value, at)
  noExtraKeys(o, ["id", "appId", "title"], at)
  return {
    id: int(o, "id", at),
    appId: nullableStr(o, "appId", at),
    title: nullableStr(o, "title", at),
  }
}

function decodeSpring(value: unknown, at: string): SpringSpec {
  const o = asObject(value, at)
  noExtraKeys(o, ["stiffness", "damping", "mass"], at)
  return {
    stiffness: num(o, "stiffness", at),
    damping: num(o, "damping", at),
    mass: num(o, "mass", at),
  }
}

function decodeAnimation(value: unknown, at: string): Animation | null {
  if (value === null) return null
  const o = asObject(value, at)
  noExtraKeys(o, ["spring"], at)
  return { spring: decodeSpring(o["spring"], `${at}.spring`) }
}

function bool(obj: Obj, key: string, at: string): boolean {
  const v = obj[key]
  if (typeof v !== "boolean") {
    throw new ProtocolError(`${at}.${key}: expected a boolean, got ${describe(v)}`)
  }
  return v
}

function decodeModifiers(value: unknown, at: string): Modifiers {
  const o = asObject(value, at)
  noExtraKeys(o, ["alt", "ctrl", "shift", "logo"], at)
  return {
    alt: bool(o, "alt", at),
    ctrl: bool(o, "ctrl", at),
    shift: bool(o, "shift", at),
    logo: bool(o, "logo", at),
  }
}

function decodePeer(value: unknown, at: string): PeerInfo {
  const o = asObject(value, at)
  noExtraKeys(o, ["id", "account", "mode", "primary", "device"], at)
  const mode = str(o, "mode", at)
  if (mode !== "view" && mode !== "interact") {
    throw new ProtocolError(`${at}.mode: expected "view" or "interact", got ${JSON.stringify(mode)}`)
  }
  return {
    id: int(o, "id", at),
    account: str(o, "account", at),
    mode,
    primary: bool(o, "primary", at),
    device: str(o, "device", at),
  }
}

function decodeWindowLayout(value: unknown, at: string): WindowLayout {
  const o = asObject(value, at)
  noExtraKeys(o, ["id", "rect", "z"], at)
  return { id: int(o, "id", at), rect: decodeRect(o["rect"], `${at}.rect`), z: int(o, "z", at) }
}

// ---------------------------------------------------------------------------
// Message decoders
// ---------------------------------------------------------------------------

/** Parse a message from the engine. Throws {@link ProtocolError} on any mismatch. */
export function decodeToShell(text: string): ToShell {
  const at = "ToShell"
  const o = asObject(parse(text, at), at)
  const t = tag(o, at)

  switch (t) {
    case "hello": {
      const where = `${at}.hello`
      noExtraKeys(
        o,
        [
          "type",
          "protocolVersion",
          "output",
          "windows",
          "focused",
          "permissions",
          "account",
          "session",
          "primary",
          "peers",
        ],
        where,
      )
      return {
        type: "hello",
        protocolVersion: int(o, "protocolVersion", where),
        output: decodeOutput(o["output"], `${where}.output`),
        windows: array(o, "windows", where).map((w, i) =>
          decodeWindowInfo(w, `${where}.windows[${i}]`),
        ),
        focused: nullableId(o, "focused", where),
        permissions: decodePermissions(o["permissions"], `${where}.permissions`),
        account: str(o, "account", where),
        session: int(o, "session", where),
        primary: bool(o, "primary", where),
        peers: array(o, "peers", where).map((p, i) => decodePeer(p, `${where}.peers[${i}]`)),
      }
    }
    case "outputChanged": {
      const where = `${at}.outputChanged`
      noExtraKeys(o, ["type", "output"], where)
      return { type: "outputChanged", output: decodeOutput(o["output"], `${where}.output`) }
    }
    case "role": {
      const where = `${at}.role`
      noExtraKeys(o, ["type", "primary"], where)
      return { type: "role", primary: bool(o, "primary", where) }
    }
    case "layout": {
      const where = `${at}.layout`
      noExtraKeys(o, ["type", "windows", "output"], where)
      return {
        type: "layout",
        windows: array(o, "windows", where).map((w, i) =>
          decodeWindowLayout(w, `${where}.windows[${i}]`),
        ),
        output: decodeOutput(o["output"], `${where}.output`),
      }
    }
    case "peers": {
      const where = `${at}.peers`
      noExtraKeys(o, ["type", "peers"], where)
      return {
        type: "peers",
        peers: array(o, "peers", where).map((p, i) => decodePeer(p, `${where}.peers[${i}]`)),
      }
    }
    case "windowOpened":
    case "windowChanged": {
      const where = `${at}.${t}`
      noExtraKeys(o, ["type", "window"], where)
      return { type: t, window: decodeWindowInfo(o["window"], `${where}.window`) }
    }
    case "windowClosed": {
      const where = `${at}.windowClosed`
      noExtraKeys(o, ["type", "id"], where)
      return { type: "windowClosed", id: int(o, "id", where) }
    }
    case "focusChanged": {
      const where = `${at}.focusChanged`
      noExtraKeys(o, ["type", "id"], where)
      return { type: "focusChanged", id: nullableId(o, "id", where) }
    }
    case "keyBinding": {
      const where = `${at}.keyBinding`
      noExtraKeys(o, ["type", "key", "modifiers"], where)
      return {
        type: "keyBinding",
        key: str(o, "key", where),
        modifiers: decodeModifiers(o["modifiers"], `${where}.modifiers`),
      }
    }
    case "appIcons": {
      const where = `${at}.appIcons`
      noExtraKeys(o, ["type", "icons"], where)
      const list = o["icons"]
      if (!Array.isArray(list)) throw new ProtocolError(`${where}.icons: expected an array`)
      return {
        type: "appIcons",
        icons: list.map((icon, i) => {
          const entry = asObject(icon, `${where}.icons[${i}]`)
          noExtraKeys(entry, ["id", "data"], `${where}.icons[${i}]`)
          return {
            id: str(entry, "id", `${where}.icons[${i}]`),
            data: str(entry, "data", `${where}.icons[${i}]`),
          }
        }),
      }
    }
    case "accounts": {
      const where = `${at}.accounts`
      noExtraKeys(o, ["type", "accounts"], where)
      const list = o["accounts"]
      if (!Array.isArray(list)) throw new ProtocolError(`${where}.accounts: expected an array`)
      return {
        type: "accounts",
        accounts: list.map((a, i) => decodeAccount(a, `${where}.accounts[${i}]`)),
      }
    }
    case "error": {
      const where = `${at}.error`
      noExtraKeys(o, ["type", "request", "message"], where)
      return { type: "error", request: str(o, "request", where), message: str(o, "message", where) }
    }
    case "fullscreenRequest": {
      const where = `${at}.fullscreenRequest`
      noExtraKeys(o, ["type", "window", "fullscreen"], where)
      return {
        type: "fullscreenRequest",
        window: num(o, "window", where) as WindowId,
        fullscreen: bool(o, "fullscreen", where),
      }
    }
    case "alreadyRunning": {
      const where = `${at}.alreadyRunning`
      noExtraKeys(o, ["type", "command", "terminal", "program", "pid"], where)
      return {
        type: "alreadyRunning",
        command: str(o, "command", where),
        terminal: bool(o, "terminal", where),
        program: str(o, "program", where),
        pid: num(o, "pid", where),
      }
    }
    case "apps": {
      const where = `${at}.apps`
      noExtraKeys(o, ["type", "apps"], where)
      const list = o["apps"]
      if (!Array.isArray(list)) throw new ProtocolError(`${where}.apps: expected an array`)
      return { type: "apps", apps: list.map((app, i) => decodeApp(app, `${where}.apps[${i}]`)) }
    }
    case "fileChooser": {
      const where = `${at}.fileChooser`
      noExtraKeys(
        o,
        ["type", "request", "save", "multiple", "directory", "title", "suggestedName"],
        where,
      )
      return {
        type: "fileChooser",
        request: int(o, "request", where),
        save: bool(o, "save", where),
        multiple: bool(o, "multiple", where),
        directory: bool(o, "directory", where),
        title: str(o, "title", where),
        suggestedName: nullableStr(o, "suggestedName", where),
      }
    }
    case "dirListing": {
      const where = `${at}.dirListing`
      noExtraKeys(o, ["type", "request", "path", "entries", "error"], where)
      const list = o["entries"]
      if (!Array.isArray(list)) throw new ProtocolError(`${where}.entries: expected an array`)
      return {
        type: "dirListing",
        request: int(o, "request", where),
        path: str(o, "path", where),
        entries: list.map((entry, i) => decodeDirEntry(entry, `${where}.entries[${i}]`)),
        error: nullableStr(o, "error", where),
      }
    }
    case "uploaded": {
      const where = `${at}.uploaded`
      noExtraKeys(o, ["type", "request", "name", "ok"], where)
      return {
        type: "uploaded",
        request: int(o, "request", where),
        name: str(o, "name", where),
        ok: bool(o, "ok", where),
      }
    }
    default:
      throw new ProtocolError(`${at}: unknown message type ${JSON.stringify(t)}`)
  }
}

function decodeDirEntry(value: unknown, at: string): DirEntry {
  const o = asObject(value, at)
  noExtraKeys(o, ["name", "dir", "size"], at)
  return {
    name: str(o, "name", at),
    dir: bool(o, "dir", at),
    size: num(o, "size", at),
  }
}

function decodeAccount(value: unknown, at: string): AccountInfo {
  const o = asObject(value, at)
  noExtraKeys(o, ["id", "name", "permissions"], at)
  return {
    id: int(o, "id", at),
    name: str(o, "name", at),
    permissions: decodePermissions(o["permissions"], `${at}.permissions`),
  }
}

function decodePermissions(value: unknown, at: string): Permissions {
  const o = asObject(value, at)
  noExtraKeys(o, ["mode", "allowedApps"], at)
  const mode = str(o, "mode", at)
  if (mode !== "view" && mode !== "interact") {
    throw new ProtocolError(`${at}.mode: expected "view" or "interact", got ${mode}`)
  }
  const allowed = o["allowedApps"]
  if (allowed !== null && !Array.isArray(allowed)) {
    throw new ProtocolError(`${at}.allowedApps: expected an array or null`)
  }
  return {
    mode,
    allowedApps:
      allowed === null
        ? null
        : allowed.map((a, i) => {
            if (typeof a !== "string") {
              throw new ProtocolError(`${at}.allowedApps[${i}]: expected a string`)
            }
            return a
          }),
  }
}

function decodeApp(value: unknown, at: string): AppEntry {
  const o = asObject(value, at)
  noExtraKeys(
    o,
    ["id", "name", "description", "exec", "icon", "categories", "terminal"],
    at,
  )
  const categories = o["categories"]
  if (!Array.isArray(categories)) throw new ProtocolError(`${at}.categories: expected an array`)
  return {
    id: str(o, "id", at),
    name: str(o, "name", at),
    description: nullableStr(o, "description", at),
    exec: str(o, "exec", at),
    icon: nullableStr(o, "icon", at),
    categories: categories.map((c, i) => {
      if (typeof c !== "string") throw new ProtocolError(`${at}.categories[${i}]: expected a string`)
      return c
    }),
    terminal: bool(o, "terminal", at),
  }
}

/** Parse a message from the shell. Throws {@link ProtocolError} on any mismatch. */
export function decodeToEngine(text: string): ToEngine {
  const at = "ToEngine"
  const o = asObject(parse(text, at), at)
  const t = tag(o, at)

  switch (t) {
    case "setLayout": {
      const where = `${at}.setLayout`
      noExtraKeys(o, ["type", "windows", "animate"], where)
      return {
        type: "setLayout",
        windows: array(o, "windows", where).map((w, i) =>
          decodeWindowLayout(w, `${where}.windows[${i}]`),
        ),
        animate: decodeAnimation(o["animate"], `${where}.animate`),
      }
    }
    case "focusWindow":
    case "closeWindow": {
      const where = `${at}.${t}`
      noExtraKeys(o, ["type", "id"], where)
      return { type: t, id: int(o, "id", where) }
    }
    case "setViewport": {
      const where = `${at}.setViewport`
      noExtraKeys(o, ["type", "width", "height", "scale"], where)
      return {
        type: "setViewport",
        width: int(o, "width", where),
        height: int(o, "height", where),
        scale: num(o, "scale", where),
      }
    }
    case "spawn": {
      const where = `${at}.spawn`
      noExtraKeys(o, ["type", "command", "terminal"], where)
      return {
        type: "spawn",
        command: str(o, "command", where),
        terminal: bool(o, "terminal", where),
      }
    }
    case "closeAndSpawn": {
      const where = `${at}.closeAndSpawn`
      noExtraKeys(o, ["type", "command", "terminal", "pid", "force"], where)
      return {
        type: "closeAndSpawn",
        command: str(o, "command", where),
        terminal: bool(o, "terminal", where),
        pid: num(o, "pid", where),
        force: bool(o, "force", where),
      }
    }
    case "pointerMotion": {
      const where = `${at}.pointerMotion`
      noExtraKeys(o, ["type", "window", "x", "y"], where)
      return {
        type: "pointerMotion",
        window: int(o, "window", where),
        x: num(o, "x", where),
        y: num(o, "y", where),
      }
    }
    case "pointerButton": {
      const where = `${at}.pointerButton`
      noExtraKeys(o, ["type", "button", "pressed"], where)
      return {
        type: "pointerButton",
        button: int(o, "button", where),
        pressed: bool(o, "pressed", where),
      }
    }
    case "pointerAxis": {
      const where = `${at}.pointerAxis`
      noExtraKeys(o, ["type", "horizontal", "vertical"], where)
      return {
        type: "pointerAxis",
        horizontal: num(o, "horizontal", where),
        vertical: num(o, "vertical", where),
      }
    }
    case "pointerLeave": {
      noExtraKeys(o, ["type"], `${at}.pointerLeave`)
      return { type: "pointerLeave" }
    }
    case "key": {
      const where = `${at}.key`
      noExtraKeys(o, ["type", "key", "pressed"], where)
      return { type: "key", key: int(o, "key", where), pressed: bool(o, "pressed", where) }
    }
    case "touchDown":
    case "touchMotion": {
      const where = `${at}.${t}`
      noExtraKeys(o, ["type", "window", "id", "x", "y"], where)
      return {
        type: t,
        window: int(o, "window", where),
        id: int(o, "id", where),
        x: num(o, "x", where),
        y: num(o, "y", where),
      }
    }
    case "touchUp": {
      const where = `${at}.touchUp`
      noExtraKeys(o, ["type", "id"], where)
      return { type: "touchUp", id: int(o, "id", where) }
    }
    case "takeControl": {
      noExtraKeys(o, ["type"], `${at}.takeControl`)
      return { type: "takeControl" }
    }
    case "setGamepad": {
      const where = `${at}.setGamepad`
      noExtraKeys(o, ["type", "enabled"], where)
      return { type: "setGamepad", enabled: bool(o, "enabled", where) }
    }
    case "setMic": {
      const where = `${at}.setMic`
      noExtraKeys(o, ["type", "enabled"], where)
      return { type: "setMic", enabled: bool(o, "enabled", where) }
    }
    case "setCamera": {
      const where = `${at}.setCamera`
      noExtraKeys(o, ["type", "enabled"], where)
      return { type: "setCamera", enabled: bool(o, "enabled", where) }
    }
    case "listDir": {
      const where = `${at}.listDir`
      noExtraKeys(o, ["type", "request", "path"], where)
      return { type: "listDir", request: int(o, "request", where), path: str(o, "path", where) }
    }
    case "fileUpload": {
      const where = `${at}.fileUpload`
      noExtraKeys(o, ["type", "request", "name", "size"], where)
      return {
        type: "fileUpload",
        request: int(o, "request", where),
        name: str(o, "name", where),
        size: num(o, "size", where),
      }
    }
    case "fileUploadDone": {
      const where = `${at}.fileUploadDone`
      noExtraKeys(o, ["type", "request"], where)
      return { type: "fileUploadDone", request: int(o, "request", where) }
    }
    case "fileChosen": {
      const where = `${at}.fileChosen`
      noExtraKeys(o, ["type", "request", "paths"], where)
      const list = o["paths"]
      if (!Array.isArray(list)) throw new ProtocolError(`${where}.paths: expected an array`)
      return {
        type: "fileChosen",
        request: int(o, "request", where),
        paths: list.map((p, i) => {
          if (typeof p !== "string") {
            throw new ProtocolError(`${where}.paths[${i}]: expected a string`)
          }
          return p
        }),
      }
    }
    case "fileCancel": {
      const where = `${at}.fileCancel`
      noExtraKeys(o, ["type", "request"], where)
      return { type: "fileCancel", request: int(o, "request", where) }
    }
    case "gamepadButton": {
      const where = `${at}.gamepadButton`
      noExtraKeys(o, ["type", "button", "pressed"], where)
      return {
        type: "gamepadButton",
        button: int(o, "button", where),
        pressed: bool(o, "pressed", where),
      }
    }
    case "gamepadAxis": {
      const where = `${at}.gamepadAxis`
      noExtraKeys(o, ["type", "axis", "value"], where)
      return { type: "gamepadAxis", axis: int(o, "axis", where), value: num(o, "value", where) }
    }
    case "setAudio": {
      const where = `${at}.setAudio`
      noExtraKeys(o, ["type", "enabled", "local", "opus", "quality"], where)
      const quality = o["quality"] ?? "auto"
      if (
        quality !== "auto" &&
        quality !== "high" &&
        quality !== "medium" &&
        quality !== "low"
      ) {
        throw new ProtocolError(`${where}.quality: not an audio quality: ${String(quality)}`)
      }
      return {
        type: "setAudio",
        enabled: bool(o, "enabled", where),
        local: bool(o, "local", where),
        opus: bool(o, "opus", where),
        quality,
      }
    }
    case "endSession": {
      const where = `${at}.endSession`
      noExtraKeys(o, ["type", "session"], where)
      return { type: "endSession", session: int(o, "session", where) }
    }
    case "setSessionMode": {
      const where = `${at}.setSessionMode`
      noExtraKeys(o, ["type", "session", "mode"], where)
      const mode = str(o, "mode", where)
      if (mode !== "view" && mode !== "interact") {
        throw new ProtocolError(
          `${where}.mode: expected "view" or "interact", got ${JSON.stringify(mode)}`,
        )
      }
      return { type: "setSessionMode", session: int(o, "session", where), mode }
    }
    case "setStreams": {
      const where = `${at}.setStreams`
      noExtraKeys(o, ["type", "windows", "codecs"], where)
      return {
        type: "setStreams",
        windows: array(o, "windows", where).map((w, i) => {
          if (typeof w !== "number" || !Number.isInteger(w)) {
            throw new ProtocolError(`${where}.windows[${i}]: expected an integer window id`)
          }
          return w
        }),
        codecs: array(o, "codecs", where).map((c, i) => {
          const value = String(c)
          if (value !== "hevc" && value !== "h264") {
            throw new ProtocolError(`${where}.codecs[${i}]: unknown codec ${value}`)
          }
          return value
        }),
      }
    }
    default:
      throw new ProtocolError(`${at}: unknown message type ${JSON.stringify(t)}`)
  }
}

function parse(text: string, at: string): unknown {
  try {
    return JSON.parse(text)
  } catch (err) {
    throw new ProtocolError(`${at}: invalid JSON: ${(err as Error).message}`)
  }
}

/**
 * Serialise a message for the wire.
 *
 * Field order follows the Rust struct declaration order so a diff of two
 * captures lines up, though nothing depends on it.
 */
export function encode(message: ToShell | ToEngine): string {
  return JSON.stringify(message)
}

// ---------------------------------------------------------------------------
// Binary frame transport
//
// Window pixels do not travel as JSON. They arrive as WebSocket *binary*
// frames with the fixed header below, on the same socket: text is control,
// binary is pixels. Mirrors the Rust side in `crates/lwfa-proto`.
// ---------------------------------------------------------------------------

/** Identifies an lwfa binary frame. ASCII "LWFA". */
export const FRAME_MAGIC = [0x4c, 0x57, 0x46, 0x41] as const

/** Bumped when the header layout changes. Independent of PROTOCOL_VERSION. */
export const FRAME_VERSION = 0

/** Bytes before the payload. */
export const FRAME_HEADER_LEN = 24

/** Bit 0 of the flags byte at offset 6. */
const FLAG_KEYFRAME = 1 << 0

export const FrameFormat = {
  /** Whole-image, always self-contained. The engine's fallback when it has no
   *  hardware encoder session left (8 concurrent on the dev GPU). */
  Jpeg: 0,
  /** H.264 Annex B, SPS/PPS repeated on every keyframe. The normal path. */
  H264: 1,
  /** HEVC Annex B, parameter sets repeated on every keyframe. Same shape as
   *  H.264, roughly a third fewer bits, sent only where the client said it can
   *  decode it. */
  Hevc: 2,
} as const
export type FrameFormat = (typeof FrameFormat)[keyof typeof FrameFormat]

export interface FrameHeader {
  window: WindowId
  width: number
  height: number
  format: FrameFormat
  /**
   * A decoder can start here. Always true for JPEG; true for H.264 IDRs.
   *
   * A browser attaching mid-stream must discard frames until this is true, or
   * it feeds its decoder deltas with no reference picture.
   */
  keyframe: boolean
}

export interface DecodedFrame {
  header: FrameHeader
  payload: Uint8Array
}

/**
 * Parse a binary frame.
 *
 * Returns null rather than throwing or partially decoding, so a malformed or
 * foreign binary message is dropped instead of being drawn as garbage.
 */
/** Magic for an audio chunk. Distinct from `FRAME_MAGIC`; see the Rust side. */
export const AUDIO_MAGIC = [0x4c, 0x57, 0x46, 0x50] as const // "LWFP"

/** Bytes before an audio payload. */
export const AUDIO_HEADER_LEN = 16

// A const object rather than an `enum`, matching `FrameFormat`. Node's
// type-stripping loader refuses enums, and the end-to-end scripts import this
// module directly.
export const AudioFormat = {
  /** Interleaved signed 16-bit little-endian. */
  Pcm16: 0,
  /** Opus, one packet per message, 20ms each. Roughly a twelfth of PCM. */
  Opus: 1,
} as const
export type AudioFormat = (typeof AudioFormat)[keyof typeof AudioFormat]

export interface AudioHeader {
  format: AudioFormat
  channels: number
  sampleRate: number
  /** Sample frames in the payload, per channel. */
  frames: number
}

export interface DecodedAudio {
  header: AudioHeader
  /** Interleaved signed 16-bit samples, little-endian. */
  payload: Uint8Array
}

/**
 * Parse an audio chunk, or return null if this is not one.
 *
 * Returning null is the *normal* path for a video frame: audio and pixels
 * share one socket, so the reader tries this and `decodeFrame` in turn and the
 * magic decides. Which is why nothing is logged here.
 */
export function decodeAudio(buffer: ArrayBuffer): DecodedAudio | null {
  if (buffer.byteLength < AUDIO_HEADER_LEN) return null
  const bytes = new Uint8Array(buffer)

  for (let i = 0; i < AUDIO_MAGIC.length; i++) {
    if (bytes[i] !== AUDIO_MAGIC[i]) return null
  }
  if (bytes[4] !== FRAME_VERSION) return null
  const format = bytes[5]
  if (format !== AudioFormat.Pcm16 && format !== AudioFormat.Opus) return null

  const channels = bytes[6] ?? 0
  if (channels === 0 || channels > 8) return null

  const view = new DataView(buffer)
  const sampleRate = view.getUint32(8, true)
  const frames = view.getUint32(12, true)
  if (sampleRate === 0 || frames === 0) return null

  // For PCM the payload must be exactly what the header claims. A short chunk
  // played as-is would shift every later sample and turn the stream into
  // noise.
  //
  // An Opus packet has no such relationship: its length is whatever the
  // encoder produced for those frames, which is the entire point. `frames`
  // still says how much audio it represents, which is what the decoder needs
  // to keep the clock straight.
  if (format === AudioFormat.Pcm16) {
    const expected = frames * channels * 2
    if (buffer.byteLength - AUDIO_HEADER_LEN !== expected) return null
  } else if (buffer.byteLength <= AUDIO_HEADER_LEN) {
    return null
  }

  return {
    header: { format, channels, sampleRate, frames },
    payload: bytes.subarray(AUDIO_HEADER_LEN),
  }
}

export function decodeFrame(buffer: ArrayBuffer): DecodedFrame | null {
  if (buffer.byteLength < FRAME_HEADER_LEN) return null
  const bytes = new Uint8Array(buffer)

  for (let i = 0; i < FRAME_MAGIC.length; i++) {
    if (bytes[i] !== FRAME_MAGIC[i]) return null
  }
  if (bytes[4] !== FRAME_VERSION) return null
  const format = bytes[5]
  if (format !== FrameFormat.Jpeg && format !== FrameFormat.H264 && format !== FrameFormat.Hevc)
    return null
  const keyframe = ((bytes[6] ?? 0) & FLAG_KEYFRAME) !== 0

  const view = new DataView(buffer)
  // Window ids are u64 on the wire. Reading as BigInt and narrowing keeps this
  // honest: ids beyond 2^53 would silently collide if read as a float, and
  // that would show pixels in the wrong window.
  const id = view.getBigUint64(8, true)
  if (id > BigInt(Number.MAX_SAFE_INTEGER)) return null

  const width = view.getUint32(16, true)
  const height = view.getUint32(20, true)
  if (width === 0 || height === 0) return null

  return {
    header: { window: Number(id), width, height, format, keyframe },
    payload: bytes.subarray(FRAME_HEADER_LEN),
  }
}
