/**
 * The shell protocol, TypeScript side.
 *
 * Mirrors `crates/lwfa-proto`. Read that crate's module docs for the design;
 * this file is the wire mapping and a strict runtime decoder.
 *
 * # Why a runtime decoder and not just types
 *
 * TypeScript types vanish at runtime, so `JSON.parse(...) as ToShell` asserts
 * nothing. If the engine renamed `appId` and this side did not, the field would
 * quietly read `undefined` and windows would lose their names with no error
 * anywhere. The decoders below check the shape for real, and
 * `test/parity.test.ts` runs them against fixtures generated by the Rust
 * implementation.
 *
 * Decoding is strict about unknown fields, matching `deny_unknown_fields` on
 * the Rust side. Protocol evolution goes through {@link PROTOCOL_VERSION}, not
 * through silently tolerated extra keys.
 */

/** Bumped on any breaking change. Must equal the Rust `PROTOCOL_VERSION`. */
export const PROTOCOL_VERSION = 0

/** Engine-assigned window handle. A bare number on the wire. */
export type WindowId = number

export interface Output {
  width: number
  height: number
  scale: number
}

export interface Rect {
  x: number
  y: number
  width: number
  height: number
}

export interface WindowInfo {
  id: WindowId
  appId: string | null
  title: string | null
}

export interface SpringSpec {
  stiffness: number
  damping: number
  mass: number
}

export interface Animation {
  spring: SpringSpec
}

export interface WindowLayout {
  id: WindowId
  rect: Rect
  z: number
}

/**
 * A pointer button, Linux evdev numbering (`BTN_LEFT` = 0x110).
 * Not the browser's 0/1/2, which is a different numbering entirely.
 */
export type ButtonCode = number

/**
 * A key, Linux evdev numbering (`KEY_A` = 30).
 *
 * Derived from `KeyboardEvent.code` (the physical key), never from
 * `KeyboardEvent.key` (the character), or the layout would be applied twice.
 * See `packages/shell/src/input.ts`.
 */
export type KeyCode = number

/** Keyboard modifier state at the time of a key press. */
export interface Modifiers {
  alt: boolean
  ctrl: boolean
  shift: boolean
  /** The Super/Windows/Command key. */
  logo: boolean
}

export type ToShell =
  | {
      type: "hello"
      protocolVersion: number
      output: Output
      windows: WindowInfo[]
      focused: WindowId | null
      permissions: Permissions
      /** Which account this is. "owner" for AUTH_PASS. */
      account: string
    }
  | { type: "outputChanged"; output: Output }
  | { type: "windowOpened"; window: WindowInfo }
  | { type: "windowChanged"; window: WindowInfo }
  | { type: "windowClosed"; id: WindowId }
  | { type: "focusChanged"; id: WindowId | null }
  /**
   * A modified key the engine did not claim for itself.
   *
   * "Focus the column to the left" is layout policy, so it belongs to the
   * shell. `key` is an xkb keysym name such as `"h"`, `"Left"` or `"Return"`.
   */
  | { type: "keyBinding"; key: string; modifiers: Modifiers }
  /**
   * Installed applications, in reply to `listApps`.
   *
   * On request rather than in `hello`, because scanning the desktop entries
   * touches the filesystem and most sessions never open the launcher.
   */
  | { type: "apps"; apps: AppEntry[] }
  /** The accounts on this machine. Never contains a password or a hash. */
  | { type: "accounts"; accounts: AccountInfo[] }
  /**
   * A request with a visible result did not happen, and why.
   *
   * Distinct from a dropped message: this exists so the UI can say "that name
   * is taken" rather than leaving a dialog waiting for a reply.
   */
  | { type: "error"; request: string; message: string }

/**
 * What a connected session is allowed to do.
 *
 * Advisory here: the shell uses it to grey out what it cannot use. The engine
 * enforces it. A permission checked only in the browser is not a permission,
 * it is a suggestion.
 */
export interface Permissions {
  mode: SessionMode
  /** Desktop entry ids this session may launch. `null` means all of them. */
  allowedApps: string[] | null
}

export type SessionMode = "view" | "interact"

/** One account, as the Access panel sees it. */
export interface AccountInfo {
  id: number
  name: string
  permissions: Permissions
}

/** One launchable application, from a freedesktop `.desktop` entry. */
export interface AppEntry {
  /** The desktop file's basename without its extension. */
  id: string
  name: string
  description: string | null
  /** `Exec=`, with the freedesktop field codes (%f, %U, ...) removed. */
  exec: string
  /** An icon *name*, not a path. The shell has no icon theme; this is a hint. */
  icon: string | null
  categories: string[]
  terminal: boolean
}

export type ToEngine =
  | { type: "setLayout"; windows: WindowLayout[]; animate: Animation | null }
  | { type: "focusWindow"; id: WindowId }
  | { type: "closeWindow"; id: WindowId }
  | { type: "spawn"; command: string }
  /** Ask for the installed applications. Answered with `apps`. */
  | { type: "listApps" }
  /** Account administration. All four require the owner. */
  | { type: "listAccounts" }
  | { type: "createAccount"; name: string; password: string; permissions: Permissions }
  | { type: "updateAccount"; id: number; permissions: Permissions; password: string | null }
  | { type: "deleteAccount"; id: number }
  /**
   * Which windows the shell wants pixels for. Total: anything not listed stops
   * streaming. A shell compositing natively asks for none.
   */
  /**
   * Which windows to stream, and whether this client can decode H.264.
   *
   * `h264: false` is not hypothetical: WebCodecs `VideoDecoder` is only
   * exposed in a secure context, so a browser reached over plain HTTP on a LAN
   * address has no H.264 decoder while the same browser on localhost does.
   */
  | { type: "setStreams"; windows: WindowId[]; h264: boolean }
  /**
   * Pointer moved within a window. Coordinates are window-relative logical
   * pixels, because during an animation the engine's actual window position
   * differs from the shell's target and output-relative coordinates would land
   * clicks where the window is heading rather than where it is.
   */
  | { type: "pointerMotion"; window: WindowId; x: number; y: number }
  | { type: "pointerButton"; button: ButtonCode; pressed: boolean }
  | { type: "pointerAxis"; horizontal: number; vertical: number }
  | { type: "pointerLeave" }
  | { type: "key"; key: KeyCode; pressed: boolean }
  /** Touch is first-class, not synthesised into pointer events. */
  | { type: "touchDown"; window: WindowId; id: number; x: number; y: number }
  | { type: "touchMotion"; window: WindowId; id: number; x: number; y: number }
  | { type: "touchUp"; id: number }

/** Motion's defaults, matching `SpringSpec::default` on the Rust side. */
export const DEFAULT_SPRING: SpringSpec = { stiffness: 100, damping: 10, mass: 1 }

export class ProtocolError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "ProtocolError"
  }
}

// ---------------------------------------------------------------------------
// Strict field readers
//
// Hand-rolled rather than pulled from a validation library: the shell ships to
// a phone over a mobile connection, this is the only place that needs it, and
// being explicit about rejecting unknown keys is the entire point.
// ---------------------------------------------------------------------------

type Obj = Record<string, unknown>

function asObject(value: unknown, at: string): Obj {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new ProtocolError(`${at}: expected an object, got ${describe(value)}`)
  }
  return value as Obj
}

function describe(value: unknown): string {
  if (value === null) return "null"
  if (Array.isArray(value)) return "an array"
  return typeof value
}

/** Reject any key the schema does not name, mirroring `deny_unknown_fields`. */
function noExtraKeys(obj: Obj, allowed: readonly string[], at: string): void {
  for (const key of Object.keys(obj)) {
    if (!allowed.includes(key)) {
      throw new ProtocolError(
        `${at}: unknown field ${JSON.stringify(key)}, expected one of ${allowed.join(", ")}`,
      )
    }
  }
}

function num(obj: Obj, key: string, at: string): number {
  const v = obj[key]
  if (typeof v !== "number" || !Number.isFinite(v)) {
    throw new ProtocolError(`${at}.${key}: expected a finite number, got ${describe(v)}`)
  }
  return v
}

function int(obj: Obj, key: string, at: string): number {
  const v = num(obj, key, at)
  if (!Number.isInteger(v)) {
    throw new ProtocolError(`${at}.${key}: expected an integer, got ${v}`)
  }
  return v
}

function str(obj: Obj, key: string, at: string): string {
  const v = obj[key]
  if (typeof v !== "string") {
    throw new ProtocolError(`${at}.${key}: expected a string, got ${describe(v)}`)
  }
  return v
}

/**
 * Rust `Option<T>` serialises to `null`, never to an absent key, so a missing
 * key is a real error rather than an implicit None.
 */
function nullableStr(obj: Obj, key: string, at: string): string | null {
  const v = obj[key]
  if (v === null) return null
  if (typeof v !== "string") {
    throw new ProtocolError(`${at}.${key}: expected a string or null, got ${describe(v)}`)
  }
  return v
}

function nullableId(obj: Obj, key: string, at: string): WindowId | null {
  const v = obj[key]
  if (v === null) return null
  return int(obj, key, at)
}

function array(obj: Obj, key: string, at: string): unknown[] {
  const v = obj[key]
  if (!Array.isArray(v)) {
    throw new ProtocolError(`${at}.${key}: expected an array, got ${describe(v)}`)
  }
  return v
}

function tag(obj: Obj, at: string): string {
  const v = obj["type"]
  if (typeof v !== "string") {
    throw new ProtocolError(`${at}: missing discriminant "type"`)
  }
  return v
}

// ---------------------------------------------------------------------------
// Component decoders
// ---------------------------------------------------------------------------

function decodeOutput(value: unknown, at: string): Output {
  const o = asObject(value, at)
  noExtraKeys(o, ["width", "height", "scale"], at)
  return { width: int(o, "width", at), height: int(o, "height", at), scale: num(o, "scale", at) }
}

function decodeRect(value: unknown, at: string): Rect {
  const o = asObject(value, at)
  noExtraKeys(o, ["x", "y", "width", "height"], at)
  return {
    x: num(o, "x", at),
    y: num(o, "y", at),
    width: num(o, "width", at),
    height: num(o, "height", at),
  }
}

function decodeWindowInfo(value: unknown, at: string): WindowInfo {
  const o = asObject(value, at)
  noExtraKeys(o, ["id", "appId", "title"], at)
  return {
    id: int(o, "id", at),
    appId: nullableStr(o, "appId", at),
    title: nullableStr(o, "title", at),
  }
}

function decodeSpring(value: unknown, at: string): SpringSpec {
  const o = asObject(value, at)
  noExtraKeys(o, ["stiffness", "damping", "mass"], at)
  return {
    stiffness: num(o, "stiffness", at),
    damping: num(o, "damping", at),
    mass: num(o, "mass", at),
  }
}

function decodeAnimation(value: unknown, at: string): Animation | null {
  if (value === null) return null
  const o = asObject(value, at)
  noExtraKeys(o, ["spring"], at)
  return { spring: decodeSpring(o["spring"], `${at}.spring`) }
}

function bool(obj: Obj, key: string, at: string): boolean {
  const v = obj[key]
  if (typeof v !== "boolean") {
    throw new ProtocolError(`${at}.${key}: expected a boolean, got ${describe(v)}`)
  }
  return v
}

function decodeModifiers(value: unknown, at: string): Modifiers {
  const o = asObject(value, at)
  noExtraKeys(o, ["alt", "ctrl", "shift", "logo"], at)
  return {
    alt: bool(o, "alt", at),
    ctrl: bool(o, "ctrl", at),
    shift: bool(o, "shift", at),
    logo: bool(o, "logo", at),
  }
}

function decodeWindowLayout(value: unknown, at: string): WindowLayout {
  const o = asObject(value, at)
  noExtraKeys(o, ["id", "rect", "z"], at)
  return { id: int(o, "id", at), rect: decodeRect(o["rect"], `${at}.rect`), z: int(o, "z", at) }
}

// ---------------------------------------------------------------------------
// Message decoders
// ---------------------------------------------------------------------------

/** Parse a message from the engine. Throws {@link ProtocolError} on any mismatch. */
export function decodeToShell(text: string): ToShell {
  const at = "ToShell"
  const o = asObject(parse(text, at), at)
  const t = tag(o, at)

  switch (t) {
    case "hello": {
      const where = `${at}.hello`
      noExtraKeys(
        o,
        ["type", "protocolVersion", "output", "windows", "focused", "permissions", "account"],
        where,
      )
      return {
        type: "hello",
        protocolVersion: int(o, "protocolVersion", where),
        output: decodeOutput(o["output"], `${where}.output`),
        windows: array(o, "windows", where).map((w, i) =>
          decodeWindowInfo(w, `${where}.windows[${i}]`),
        ),
        focused: nullableId(o, "focused", where),
        permissions: decodePermissions(o["permissions"], `${where}.permissions`),
        account: str(o, "account", where),
      }
    }
    case "outputChanged": {
      const where = `${at}.outputChanged`
      noExtraKeys(o, ["type", "output"], where)
      return { type: "outputChanged", output: decodeOutput(o["output"], `${where}.output`) }
    }
    case "windowOpened":
    case "windowChanged": {
      const where = `${at}.${t}`
      noExtraKeys(o, ["type", "window"], where)
      return { type: t, window: decodeWindowInfo(o["window"], `${where}.window`) }
    }
    case "windowClosed": {
      const where = `${at}.windowClosed`
      noExtraKeys(o, ["type", "id"], where)
      return { type: "windowClosed", id: int(o, "id", where) }
    }
    case "focusChanged": {
      const where = `${at}.focusChanged`
      noExtraKeys(o, ["type", "id"], where)
      return { type: "focusChanged", id: nullableId(o, "id", where) }
    }
    case "keyBinding": {
      const where = `${at}.keyBinding`
      noExtraKeys(o, ["type", "key", "modifiers"], where)
      return {
        type: "keyBinding",
        key: str(o, "key", where),
        modifiers: decodeModifiers(o["modifiers"], `${where}.modifiers`),
      }
    }
    case "accounts": {
      const where = `${at}.accounts`
      noExtraKeys(o, ["type", "accounts"], where)
      const list = o["accounts"]
      if (!Array.isArray(list)) throw new ProtocolError(`${where}.accounts: expected an array`)
      return {
        type: "accounts",
        accounts: list.map((a, i) => decodeAccount(a, `${where}.accounts[${i}]`)),
      }
    }
    case "error": {
      const where = `${at}.error`
      noExtraKeys(o, ["type", "request", "message"], where)
      return { type: "error", request: str(o, "request", where), message: str(o, "message", where) }
    }
    case "apps": {
      const where = `${at}.apps`
      noExtraKeys(o, ["type", "apps"], where)
      const list = o["apps"]
      if (!Array.isArray(list)) throw new ProtocolError(`${where}.apps: expected an array`)
      return { type: "apps", apps: list.map((app, i) => decodeApp(app, `${where}.apps[${i}]`)) }
    }
    default:
      throw new ProtocolError(`${at}: unknown message type ${JSON.stringify(t)}`)
  }
}

function decodeAccount(value: unknown, at: string): AccountInfo {
  const o = asObject(value, at)
  noExtraKeys(o, ["id", "name", "permissions"], at)
  return {
    id: int(o, "id", at),
    name: str(o, "name", at),
    permissions: decodePermissions(o["permissions"], `${at}.permissions`),
  }
}

function decodePermissions(value: unknown, at: string): Permissions {
  const o = asObject(value, at)
  noExtraKeys(o, ["mode", "allowedApps"], at)
  const mode = str(o, "mode", at)
  if (mode !== "view" && mode !== "interact") {
    throw new ProtocolError(`${at}.mode: expected "view" or "interact", got ${mode}`)
  }
  const allowed = o["allowedApps"]
  if (allowed !== null && !Array.isArray(allowed)) {
    throw new ProtocolError(`${at}.allowedApps: expected an array or null`)
  }
  return {
    mode,
    allowedApps:
      allowed === null
        ? null
        : allowed.map((a, i) => {
            if (typeof a !== "string") {
              throw new ProtocolError(`${at}.allowedApps[${i}]: expected a string`)
            }
            return a
          }),
  }
}

function decodeApp(value: unknown, at: string): AppEntry {
  const o = asObject(value, at)
  noExtraKeys(
    o,
    ["id", "name", "description", "exec", "icon", "categories", "terminal"],
    at,
  )
  const categories = o["categories"]
  if (!Array.isArray(categories)) throw new ProtocolError(`${at}.categories: expected an array`)
  return {
    id: str(o, "id", at),
    name: str(o, "name", at),
    description: nullableStr(o, "description", at),
    exec: str(o, "exec", at),
    icon: nullableStr(o, "icon", at),
    categories: categories.map((c, i) => {
      if (typeof c !== "string") throw new ProtocolError(`${at}.categories[${i}]: expected a string`)
      return c
    }),
    terminal: bool(o, "terminal", at),
  }
}

/** Parse a message from the shell. Throws {@link ProtocolError} on any mismatch. */
export function decodeToEngine(text: string): ToEngine {
  const at = "ToEngine"
  const o = asObject(parse(text, at), at)
  const t = tag(o, at)

  switch (t) {
    case "setLayout": {
      const where = `${at}.setLayout`
      noExtraKeys(o, ["type", "windows", "animate"], where)
      return {
        type: "setLayout",
        windows: array(o, "windows", where).map((w, i) =>
          decodeWindowLayout(w, `${where}.windows[${i}]`),
        ),
        animate: decodeAnimation(o["animate"], `${where}.animate`),
      }
    }
    case "focusWindow":
    case "closeWindow": {
      const where = `${at}.${t}`
      noExtraKeys(o, ["type", "id"], where)
      return { type: t, id: int(o, "id", where) }
    }
    case "spawn": {
      const where = `${at}.spawn`
      noExtraKeys(o, ["type", "command"], where)
      return { type: "spawn", command: str(o, "command", where) }
    }
    case "pointerMotion": {
      const where = `${at}.pointerMotion`
      noExtraKeys(o, ["type", "window", "x", "y"], where)
      return {
        type: "pointerMotion",
        window: int(o, "window", where),
        x: num(o, "x", where),
        y: num(o, "y", where),
      }
    }
    case "pointerButton": {
      const where = `${at}.pointerButton`
      noExtraKeys(o, ["type", "button", "pressed"], where)
      return {
        type: "pointerButton",
        button: int(o, "button", where),
        pressed: bool(o, "pressed", where),
      }
    }
    case "pointerAxis": {
      const where = `${at}.pointerAxis`
      noExtraKeys(o, ["type", "horizontal", "vertical"], where)
      return {
        type: "pointerAxis",
        horizontal: num(o, "horizontal", where),
        vertical: num(o, "vertical", where),
      }
    }
    case "pointerLeave": {
      noExtraKeys(o, ["type"], `${at}.pointerLeave`)
      return { type: "pointerLeave" }
    }
    case "key": {
      const where = `${at}.key`
      noExtraKeys(o, ["type", "key", "pressed"], where)
      return { type: "key", key: int(o, "key", where), pressed: bool(o, "pressed", where) }
    }
    case "touchDown":
    case "touchMotion": {
      const where = `${at}.${t}`
      noExtraKeys(o, ["type", "window", "id", "x", "y"], where)
      return {
        type: t,
        window: int(o, "window", where),
        id: int(o, "id", where),
        x: num(o, "x", where),
        y: num(o, "y", where),
      }
    }
    case "touchUp": {
      const where = `${at}.touchUp`
      noExtraKeys(o, ["type", "id"], where)
      return { type: "touchUp", id: int(o, "id", where) }
    }
    case "setStreams": {
      const where = `${at}.setStreams`
      noExtraKeys(o, ["type", "windows", "h264"], where)
      return {
        type: "setStreams",
        windows: array(o, "windows", where).map((w, i) => {
          if (typeof w !== "number" || !Number.isInteger(w)) {
            throw new ProtocolError(`${where}.windows[${i}]: expected an integer window id`)
          }
          return w
        }),
        h264: bool(o, "h264", where),
      }
    }
    default:
      throw new ProtocolError(`${at}: unknown message type ${JSON.stringify(t)}`)
  }
}

function parse(text: string, at: string): unknown {
  try {
    return JSON.parse(text)
  } catch (err) {
    throw new ProtocolError(`${at}: invalid JSON: ${(err as Error).message}`)
  }
}

/**
 * Serialise a message for the wire.
 *
 * Field order follows the Rust struct declaration order so a diff of two
 * captures lines up, though nothing depends on it.
 */
export function encode(message: ToShell | ToEngine): string {
  return JSON.stringify(message)
}

// ---------------------------------------------------------------------------
// Binary frame transport
//
// Window pixels do not travel as JSON. They arrive as WebSocket *binary*
// frames with the fixed header below, on the same socket: text is control,
// binary is pixels. Mirrors the Rust side in `crates/lwfa-proto`.
// ---------------------------------------------------------------------------

/** Identifies an lwfa binary frame. ASCII "LWFA". */
export const FRAME_MAGIC = [0x4c, 0x57, 0x46, 0x41] as const

/** Bumped when the header layout changes. Independent of PROTOCOL_VERSION. */
export const FRAME_VERSION = 0

/** Bytes before the payload. */
export const FRAME_HEADER_LEN = 24

/** Bit 0 of the flags byte at offset 6. */
const FLAG_KEYFRAME = 1 << 0

export const FrameFormat = {
  /** Whole-image, always self-contained. The engine's fallback when it has no
   *  hardware encoder session left (8 concurrent on the dev GPU). */
  Jpeg: 0,
  /** H.264 Annex B, SPS/PPS repeated on every keyframe. The normal path. */
  H264: 1,
} as const
export type FrameFormat = (typeof FrameFormat)[keyof typeof FrameFormat]

export interface FrameHeader {
  window: WindowId
  width: number
  height: number
  format: FrameFormat
  /**
   * A decoder can start here. Always true for JPEG; true for H.264 IDRs.
   *
   * A browser attaching mid-stream must discard frames until this is true, or
   * it feeds its decoder deltas with no reference picture.
   */
  keyframe: boolean
}

export interface DecodedFrame {
  header: FrameHeader
  payload: Uint8Array
}

/**
 * Parse a binary frame.
 *
 * Returns null rather than throwing or partially decoding, so a malformed or
 * foreign binary message is dropped instead of being drawn as garbage.
 */
export function decodeFrame(buffer: ArrayBuffer): DecodedFrame | null {
  if (buffer.byteLength < FRAME_HEADER_LEN) return null
  const bytes = new Uint8Array(buffer)

  for (let i = 0; i < FRAME_MAGIC.length; i++) {
    if (bytes[i] !== FRAME_MAGIC[i]) return null
  }
  if (bytes[4] !== FRAME_VERSION) return null
  const format = bytes[5]
  if (format !== FrameFormat.Jpeg && format !== FrameFormat.H264) return null
  const keyframe = ((bytes[6] ?? 0) & FLAG_KEYFRAME) !== 0

  const view = new DataView(buffer)
  // Window ids are u64 on the wire. Reading as BigInt and narrowing keeps this
  // honest: ids beyond 2^53 would silently collide if read as a float, and
  // that would show pixels in the wrong window.
  const id = view.getBigUint64(8, true)
  if (id > BigInt(Number.MAX_SAFE_INTEGER)) return null

  const width = view.getUint32(16, true)
  const height = view.getUint32(20, true)
  if (width === 0 || height === 0) return null

  return {
    header: { window: Number(id), width, height, format, keyframe },
    payload: bytes.subarray(FRAME_HEADER_LEN),
  }
}
