/**
 * Three-way spring parity.
 *
 * The engine (Rust) and the browser backend (TypeScript) each integrate window
 * springs locally from the same animation intent. If their curves diverge, the
 * same window animation looks different depending on whether the user is at
 * their desk or on an iPad. This test is what stops that happening silently.
 *
 * Three parties are compared:
 *   1. `fixtures/rust.samples.tsv`, generated by `cargo run -p lwfa-spring
 *      --bin gen-fixtures` from the Rust implementation.
 *   2. `packages/spring`, the TypeScript implementation.
 *   3. Upstream `motion-dom`, pinned exactly.
 *
 * Party 3 matters because the shell animates its chrome (panels, launcher,
 * notifications) with Motion. Matching it means a window animation and a panel
 * animation given the same parameters land on the same curve, which is the
 * whole point of the appearance-vocabulary design.
 *
 * If this fails after a `motion-dom` bump, that is the test doing its job.
 * Read the upstream diff, port the change to BOTH implementations, regenerate
 * fixtures, and re-pin.
 */

import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { spring as motionSpring } from "motion-dom"
import { describe, expect, it } from "vitest"
import { Spring, fromVisualDuration } from "../src/index.js"

const repoRoot = fileURLToPath(new URL("../../../", import.meta.url))

/**
 * Both implementations use f64/double and the same closed form, so the only
 * divergence should be last-bit differences in libm vs V8 for exp/sin/sinh.
 * That lands far below this. A relative epsilon so the 1920px slide is held to
 * the same standard as the 0..1 opacity fade.
 */
const EPSILON = 1e-9

function closeEnough(a: number, b: number): boolean {
  return Math.abs(a - b) <= EPSILON * Math.max(1, Math.abs(a), Math.abs(b))
}

/** Reports the actual gap, so a failure says how far off it was. */
function expectClose(actual: number, expected: number, what: string): void {
  if (!closeEnough(actual, expected)) {
    const absolute = Math.abs(actual - expected)
    const relative = absolute / Math.max(1, Math.abs(expected))
    expect.fail(
      `${what}: got ${actual}, expected ${expected} ` +
        `(abs ${absolute.toExponential(3)}, rel ${relative.toExponential(3)}, ` +
        `tolerance ${EPSILON.toExponential(0)})`,
    )
  }
}

function readRows(relativePath: string): string[][] {
  const text = readFileSync(repoRoot + relativePath, "utf8")
  return text
    .split("\n")
    .map((line) => line.trimEnd())
    .filter((line) => line !== "" && !line.startsWith("#") && !line.startsWith("name\t"))
    .map((line) => line.split("\t"))
}

/**
 * Every column in cases.tsv is required, so these are concrete numbers rather
 * than `SpringOptions`. That keeps them assignable to motion-dom's option type,
 * which forbids explicit `undefined` under `exactOptionalPropertyTypes`.
 */
interface CaseOptions {
  stiffness: number
  damping: number
  mass: number
  velocity: number
}

interface Case {
  name: string
  options: CaseOptions
  from: number
  to: number
  tMaxMs: number
  stepMs: number
}

function loadCases(): Case[] {
  const cases = readRows("fixtures/cases.tsv").map((f): Case => {
    if (f.length !== 9) {
      throw new Error(`cases.tsv: expected 9 columns, got ${f.length} in: ${f.join(" | ")}`)
    }
    const n = (i: number) => {
      const v = Number(f[i])
      if (!Number.isFinite(v)) {
        throw new Error(`cases.tsv: case "${f[0]}" column ${i + 1} is not a number: "${f[i]}"`)
      }
      return v
    }
    return {
      name: f[0]!,
      options: { stiffness: n(1), damping: n(2), mass: n(3), velocity: n(4) },
      from: n(5),
      to: n(6),
      tMaxMs: n(7),
      stepMs: n(8),
    }
  })

  if (cases.length === 0) throw new Error("cases.tsv contained no cases")
  return cases
}

interface Sample {
  tMs: number
  value: number
  velocity: number
  done: boolean
}

function loadRustSamples(): Map<string, Sample[]> {
  const byCase = new Map<string, Sample[]>()
  for (const f of readRows("fixtures/rust.samples.tsv")) {
    const name = f[0]!
    let list = byCase.get(name)
    if (!list) byCase.set(name, (list = []))
    list.push({
      tMs: Number(f[1]),
      value: Number(f[2]),
      velocity: Number(f[3]),
      done: f[4] === "1",
    })
  }
  if (byCase.size === 0) {
    throw new Error(
      "fixtures/rust.samples.tsv is empty. Run: cargo run -p lwfa-spring --bin gen-fixtures",
    )
  }
  return byCase
}

function loadRustSettle(): Map<string, number> {
  return new Map(readRows("fixtures/rust.settle.tsv").map((f) => [f[0]!, Number(f[1])]))
}

const cases = loadCases()
const rustSamples = loadRustSamples()
const rustSettle = loadRustSettle()

describe("spring parity", () => {
  it("has Rust fixtures for every declared case", () => {
    // Guards against a stale fixture file silently shrinking coverage: a new
    // case added to cases.tsv without regenerating would otherwise just not be
    // checked against Rust at all.
    const missing = cases.map((c) => c.name).filter((n) => !rustSamples.has(n))
    expect(
      missing,
      `stale fixtures. Run: cargo run -p lwfa-spring --bin gen-fixtures`,
    ).toEqual([])
  })

  describe.each(cases)("$name", (testCase) => {
    const { options, from, to, tMaxMs, stepMs } = testCase
    const ours = new Spring(options, from, to)

    // Motion resolves from physics keys (not duration/bounce) when
    // stiffness/damping/mass are present, which is the path we ported.
    const theirs = motionSpring({ keyframes: [from, to], ...options })

    // `velocity` is optional on motion-dom's generator type. If it ever stops
    // being provided, the velocity comparison below would silently vanish, so
    // fail loudly instead.
    const theirVelocity = theirs.velocity
    if (!theirVelocity) {
      throw new Error("motion-dom generator no longer exposes velocity()")
    }

    const stepCount = Math.floor(tMaxMs / stepMs)
    // Derived from the index rather than accumulated, so sample times match the
    // Rust generator exactly instead of drifting by repeated float addition.
    const times = Array.from({ length: stepCount + 1 }, (_, i) => i * stepMs)

    it("matches the Rust implementation", () => {
      const expected = rustSamples.get(testCase.name)!
      expect(expected.length).toBe(times.length)

      for (const [i, tMs] of times.entries()) {
        const want = expected[i]!
        expect(want.tMs, `sample ${i} time`).toBe(tMs)

        const state = ours.stateAt(tMs)
        expectClose(state.value, want.value, `t=${tMs}ms value`)
        expectClose(ours.velocityAt(tMs), want.velocity, `t=${tMs}ms velocity`)
        expect(state.done, `t=${tMs}ms done`).toBe(want.done)
      }
    })

    it("matches upstream motion-dom", () => {
      for (const tMs of times) {
        const state = ours.stateAt(tMs)
        const upstream = theirs.next(tMs)
        expectClose(state.value, upstream.value, `t=${tMs}ms value vs motion`)
        expectClose(ours.velocityAt(tMs), theirVelocity(tMs), `t=${tMs}ms velocity vs motion`)
        expect(state.done, `t=${tMs}ms done vs motion`).toBe(upstream.done)
      }
    })

    it("agrees with Rust on settle time", () => {
      // Backends schedule animation lifetime off this, so a mismatch means one
      // side stops animating while the other is still moving.
      expect(ours.settleTimeMs(30_000, 4)).toBe(rustSettle.get(testCase.name))
    })

    it("starts at the origin and ends on the target", () => {
      expectClose(ours.valueAt(0), from, "value at t=0")
      expect(ours.stateAt(ours.settleTimeMs(30_000, 4)).value).toBe(to)
    })

    it("produces only finite samples", () => {
      // The overdamped sinh/cosh cap exists for this. Without it, large t
      // overflows to Infinity and a window would vanish rather than settle.
      for (const tMs of [...times, 1e6]) {
        expect(Number.isFinite(ours.valueAt(tMs)), `value at t=${tMs}ms`).toBe(true)
        expect(Number.isFinite(ours.velocityAt(tMs)), `velocity at t=${tMs}ms`).toBe(true)
      }
    })
  })
})

describe("visual duration form", () => {
  // `fromVisualDuration` is the ergonomic API the shell will actually author
  // animations with, so it needs the same guarantee as the raw physics form.
  const visualDurations = [0.15, 0.3, 0.5, 1]
  const bounces = [0, 0.25, 0.5, 1]
  const combos = visualDurations.flatMap((visualDuration) =>
    bounces.map((bounce) => ({ visualDuration, bounce })),
  )

  it.each(combos)(
    "matches motion-dom at visualDuration=$visualDuration bounce=$bounce",
    ({ visualDuration, bounce }) => {
      const ours = new Spring(fromVisualDuration(visualDuration, bounce), 0, 100)
      const theirs = motionSpring({ keyframes: [0, 100], visualDuration, bounce })

      for (let tMs = 0; tMs <= 2000; tMs += 8) {
        const state = ours.stateAt(tMs)
        // Motion reuses one mutable state object across next() calls to avoid
        // GC on the hot path, so read it once per tick.
        const upstream = theirs.next(tMs)
        expectClose(state.value, upstream.value, `t=${tMs}ms value`)
        expect(state.done, `t=${tMs}ms done`).toBe(upstream.done)
      }
    },
  )
})
