/**
 * Generate the shell's layout defaults from `configs/defaults.toml`.
 *
 * The shell runs in a browser, so it cannot read the file at startup the way
 * the engine does; the values have to be in the bundle. They also have to be
 * available to `vitest` and to the Node end-to-end scripts, which rules out a
 * Vite `define`, because that only applies when Vite is doing the building.
 * Generating a plain TypeScript module covers all three.
 *
 * The output is **gitignored on purpose**, for the same reason as the spring
 * fixtures: a committed copy would let `defaults.toml` drift while everything
 * kept building against a stale snapshot. It is regenerated by `pnpm run
 * config`, which the dev, build, test and typecheck scripts all depend on.
 */

import { mkdirSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { CONFIG_PATH, readConfig } from "./config.mjs"

const OUT = fileURLToPath(new URL("../packages/shell/src/generated/config.ts", import.meta.url))

const config = readConfig()
const layout = config.layout ?? {}

const required = ["gap", "width_presets", "default_width", "min_width"]
const missing = required.filter((key) => layout[key] === undefined)
if (missing.length > 0) {
  console.error(`[layout] in ${CONFIG_PATH} is missing: ${missing.join(", ")}`)
  process.exit(1)
}

const presets = layout.width_presets
if (!Array.isArray(presets) || presets.length === 0) {
  console.error("[layout].width_presets must be a non-empty array of fractions")
  process.exit(1)
}
if (!presets.every((p) => typeof p === "number" && p > 0 && p <= 1)) {
  console.error("[layout].width_presets must all be fractions in (0, 1]")
  process.exit(1)
}
if (layout.default_width < 0 || layout.default_width >= presets.length) {
  console.error(
    `[layout].default_width is ${layout.default_width}, which is not an index into ` +
      `${presets.length} width_presets`,
  )
  process.exit(1)
}

const source = `// GENERATED by scripts/gen-config.mjs from configs/defaults.toml.
//
// Do not edit. Do not commit. Change configs/defaults.toml and re-run
// \`pnpm run config\`, which the dev, build, test and typecheck scripts do
// for you.

/**
 * Column widths, as fractions of the viewport.
 *
 * Presets rather than free resizing, because a column width change is an
 * \`xdg_shell configure\` and native apps re-layout from scratch rather than
 * reflowing. Cycling between a few known sizes keeps that rare and predictable;
 * a drag handle would fire one per frame.
 */
export const WIDTH_PRESETS = [${presets.join(", ")}] as const

/** Gap between columns, between stacked windows, and at the output edge. */
export const GAP = ${layout.gap}

/** Which preset a new column gets. An index into WIDTH_PRESETS. */
export const DEFAULT_WIDTH = ${layout.default_width}

/** Floor on column width, so a phone-width viewport stays usable. */
export const MIN_WIDTH = ${layout.min_width}
`

mkdirSync(fileURLToPath(new URL("../packages/shell/src/generated/", import.meta.url)), {
  recursive: true,
})
writeFileSync(OUT, source)
console.log(`wrote ${OUT}`)
